### ISSUE TITLE
possible switching pool bug

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#100]
I think this is not a bug I introduced in my fork, so I'm posting it here.
In testing with MPH's auto-switching port 17020, the miner doesn't seem to properly re-initialize when there is a switch between eth and etc.
 m  03:24:31|ethminer  14470 14470 14470 21076 20761 =85249Khs A14831+184:R0+0
  ?  03:24:31|GPU0  Initialising miner...
  ?  03:24:31|GPU1  Initialising miner...

After the re-initializing, one or more GPUs end up hung.

The obvious work-around is not to use a switching port (i.e. use 20535 on MPH).

**Comment by jch9678** [comment]
If you want to test this you can use port 12020. Change from ETH and ETC or vice versa on the hub worker page and monitor your miner.

Here's the page
https://miningpoolhub.com/?page=account&action=hubworkers

**Comment by miningpoolhub** [comment]
Must be some bug related to DAG creation. ETH, ETC uses same DAG most of the time so it switches smoothly without notice, but sometimes it uses different DAG and it needs to build new DAG at the middle of mining.

I tested it by pointing rig to 12020, switched ETH, EXP from hub worker page to test DAG recreation manually and found that it is working fine with 1.1.9 build.
Not tested previous versions. Maybe it's related to timing issue?

![image](https://cloud.githubusercontent.com/assets/6733455/18806462/67eaba84-8268-11e6-95d2-e151c63fde85.png)
