### ISSUE TITLE
Cmake- gcc error

### ISSUE THREAD

**Issue by leroy627** [Genoil/cpp-ethereum#101]
Building 1.1.9 from branch 110 with -DBUNDLE=cudaminer -DCOMPUTE=52 (GTX 970)
Using CUDA 8, dled yesterday from Nvidia site & apt-get install cuda afterwards
Very likely to be the new commits a few days ago, I still have the 1.1.7 git clone and that builds fine.

Log here, posting here would make scrolling annoying
https://paste.projectdev.org/sebemiwaki.lua

**Comment by Perfect-Web** [comment]
@Genoil i confirm i get error with the mast on nvidia

```
[ 63%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Guards.cpp.o
[ 65%] Linking CXX shared library libdevcore.so
[ 65%] Built target devcore
[ 67%] Linking CXX shared library libethstratum.so
[ 67%] Built target ethstratum
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Perfect-Web** [comment]
and some more info

```
[ 61%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
[ 67%] Built target ethash-cl
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:207 (message):
  Error generating
  /home/miner/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:320: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 67%] Built target BuildInfo.h
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by Genoil** [comment]
I don't know. I blindly merged a PR that allegedly solved compilation issues on different platforms including Ubuntu 16 and Arch, but I never got to actually testing it myself. 

Will need to find some time for that.

**Comment by daedalus8000** [comment]
I had this error.  Added -pthread to the compile options (CMAKE_CXX_FLAGS) in cmake/EthCompilerSettings.cmake

Worked for me.

**Comment by jsapient** [comment]
like @daedalus8000 suggested, adding -pthread to CMAKE_CXX_FLAGS) solved the compiling issue i was getting on ArchLinux machines.

**Comment by theriverlethe** [comment]
Thanks, I was also able to build genoil on Arch after adding -pthread to the CXX_FLAGS.

**Comment by leroy627** [comment]
Nope, doesn't work for me while building cudaminer...
