### ISSUE TITLE
don't disconnect on unauthorized worker

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#103]
MPH started having problems this am returning false authorization responses after getting successfully authorized.  I never noticed that the "normal" function is to stop mining in this case, rather than failover.
https://github.com/Genoil/cpp-ethereum/blob/110/libstratum/EthStratumClientV2.cpp#L310

I should have some time later to day to fix/test on my fork, to be merged upstream.

**Comment by miningpoolhub** [comment]
Sorry there was some internal problem today at mph. It's all solved now. I will compensate soon.

Claymore miner disconnects when job is not updated more than 5 minutes AFAIK.
Seems like some independent timeout thing in ethminer would be good too.

**Comment by nerdralph** [comment]
Took me a while to get around to it, but I just did a Linux build including a bug fix of the unauthorized worker disconnect (it does a failover instead of disconnect).
https://github.com/nerdralph/ethminer-nr/tree/110/releases
grab version 1.2.0nr
