### ISSUE TITLE
No GPU device with sufficient memory was found. Can't GPU mine

### ISSUE THREAD

**Issue by aviadoffer** [Genoil/cpp-ethereum#104]
C:\Program Files\cpp-ethereum>ethminer.exe --list-devices -G
# Genoil's ethminer 0.9.41-genoil-1.1.7

Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1060 3GB
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 805306368
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

C:\Program Files\cpp-ethereum>ethminer.exe  -G
# Genoil's ethminer 0.9.41-genoil-1.1.7

Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

**Comment by mruepp** [comment]
Same here, same version. Standard Windows 10 install, Radeon RX480 8GB.
