### ISSUE TITLE
Linux Build isn't Solving

### ISSUE THREAD

**Issue by theriverlethe** [Genoil/cpp-ethereum#105]
After building ethminer on Arch Linux with CUDA8, running the miner doesn't solve or submit any solutions to the specified pools, but there are no error messages.  I'm using the latest 370.28 drivers with two GTX 1070's.  It doesn't matter if I use CUDA or OpenCL, although OpenCL is slightly slower.  I've tried the Windows binary with the exact same switches and everything is fine.  Any ideas?

**Comment by YamashitaRen** [comment]
I can confirm the issue.
Up-to-date Archlinux, x86_64, up-to-date master, Dual AMD7950.
Stratum or eth-proxy.

**Comment by akozlins** [comment]
I had the same problem some time ago. Upgraded my system in the beginning of October
and ethminer stopped to find solutions. After downgrading no problems.
Recently tried to find out the culprit and it seems to be related to crypto++: version 5.6.3-1 works,
with 5.6.4 and 5.6.5 no solutions.

**Comment by akozlins** [comment]
Between 5.6.3 and 5.6.4 the sha3 implementation which is used in ethminer
was changed to fips 202 spec (some padding changes, see commit 844daf0e of cryptopp).
This implementation is not the one used for keccak and the ethminer does not work.

**Comment by mmstick** [comment]
Experienced the same issue, and resolved it after manually installing https://archive.archlinux.org/repos/2016/04/30/extra/os/x86_64/crypto%2B%2B-5.6.3-1-x86_64.pkg.tar.xz

**Comment by theriverlethe** [comment]
That worked for me.  How do I prevent a package from upgrading in Arch?  Are there plans to fix this in the future?
