### ISSUE TITLE
out of memory using cuda

### ISSUE THREAD

**Issue by kd0frg** [Genoil/cpp-ethereum#120]
Found suitable CUDA device [GeForce GTX 760] with 2147483648 bytes of GPU memory
  i  16:28:08|stratum  Connecting to stratum server daggerhashimoto.eu.nicehash.com:3353
  i  16:28:08|stratum  Connected!
  i  16:28:08|stratum  Starting farm
  i  16:28:12|stratum  Extranonce set to 0024cb
  i  16:28:12|stratum  Subscribed to stratum server
  i  16:28:12|stratum  Authorized worker 1CJimUU4g74s825ZYbitCxwP15z6Mxp6hh.WORKER-NAME
  i  16:28:12|stratum  Difficulty set to 0.05
  i  16:28:12|stratum  New job 0000003afc593b28 target 0013ffec header 36e6e708
  i  16:28:12|cudaminer0  set work; seed: #9336adfd, target: #00000013ffec
  i  16:28:12|cudaminer0  Initialising miner...
Using device: GeForce GTX 760 (Compute 3.0)
CUDA error in func 'ethash_cuda_miner::init' at line 243 : out of memory.

is there a way to fix this?

**Comment by bilouw** [comment]
Anyone know how to solve this issue ?

**Comment by Genoil** [comment]
Only a GPU with > 2 GB RAM will work these days.

**Comment by bilouw** [comment]
Ok, so it's not possible with my nvidia 860m 2GB ? 
shit ...
i tried with no flag, with the original ethminer, so on the CPU. 
It work, but i solve a problem once in a day lol !
is it normal ?
even with a low hashrate, i thought that i could solved problem every 20-30min ...
why this is not working ?

Thanks for your help !

**Comment by igormcoelho** [comment]
I had the same "out of memory" problem, using a GTX 830M 2002MiB, in Ubuntu 16.04... after a reboot, I run "nvidia-smi" and 98MiB of device memory was occupied by Xorg and compiz, then I got ethminer running with 1890MiB (total 1988MiB of 2002MiB, only 14MiB left!). As the DAG grows, it won't be possible anymore, but I enjoy while I can :)
