### ISSUE TITLE
Insuffisent memory on 4Gb card (Rx480)

### ISSUE THREAD

**Issue by irmas** [Genoil/cpp-ethereum#132]
Hello,
I am getting the `No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument` error when running .`/ethminer -M -G`

I have a Radeon Rx 480 (with 4Gb memory) so I should have enough memory.

I am running Arch Linux (up to date) and am using  Genoil's ethminer 0.9.41-genoil-1.1.7 and 
 the  [opencl-amd package](https://aur.archlinux.org/packages/opencl-amd/)  that

>  uses the open source AMDGPU drivers, and only the proprietary OpenCL component. [wiki page](https://wiki.archlinux.org/index.php/AMDGPU#AMDGPU_PRO)

`ls /etc/OpenCL/vendors ` returns `amdocl64.icd` 

Thanks

**Comment by ITwrx** [comment]
i'm running arch too and i  get the same thing when i run ethminer but i have 8GB rx480. If i run ethminer as root user it sees the card just fine but craps out with hash rate and curl error.
