### ISSUE TITLE
Repository No Longer Maintained?

### ISSUE THREAD

**Issue by mmstick** [Genoil/cpp-ethereum#135]
It's been half a year and many critical changes / pull requests still have not been accepted. If this repository is no longer maintained, then I will create a fork and request authors to re-submit their work to the new fork.

**Comment by brutuscat** [comment]
@ mmstick you could fork and merge stuff PRs in your own fork ;)

**Comment by mmstick** [comment]
@brutuscat I'm probably going to do just that soon. I need this fork to be in proper condition because it sucks having to keep my cryptocpp lib on Arch Linux held back even though there's a simple PR that solves that issue with a few LOC.

**Comment by Genoil** [comment]
Please, by all means, fork away! Unfortunately I don't have time to maintain this software any longer. Good luck!

**Comment by lhirlimann** [comment]
@mmstick cool let us know when you'll fork

**Comment by mmstick** [comment]
It's already done.

**Comment by akonyer** [comment]
Would you mind releasing an updated windows executable in your fork? It's just so much easier than getting the dependencies ready to compile the source myself. If not I totally understand.

**Comment by mmstick** [comment]
I don't have any computers running Windows, so I can't provide support
there. My target is rolling release Linux distributions like Arch Linux.
Others are free to package for Windows if they wish though.
