### ISSUE TITLE
Console output shows 0.00 MH/s hashrate every few lines

### ISSUE THREAD

**Issue by marcofranssen** [Genoil/cpp-ethereum#137]
Is following normal when using the miner?

```
  m  14:52:15|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:15|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:16|main  Mining on PoWhash #dcbc6ba3 : 5.14MH/s [A1+0:R0+0:F0]
  m  14:52:16|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:16|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:16|main  Mining on PoWhash #dcbc6ba3 : 5.09MH/s [A1+0:R0+0:F0]
  m  14:52:16|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:17|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:17|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:17|main  Mining on PoWhash #dcbc6ba3 : 5.12MH/s [A1+0:R0+0:F0]
  m  14:52:17|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:17|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:18|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:18|main  Mining on PoWhash #dcbc6ba3 : 5.14MH/s [A1+0:R0+0:F0]
  m  14:52:18|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:18|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:18|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:19|main  Mining on PoWhash #dcbc6ba3 : 5.07MH/s [A1+0:R0+0:F0]
  m  14:52:19|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:19|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:19|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:20|main  Mining on PoWhash #dcbc6ba3 : 5.14MH/s [A1+0:R0+0:F0]
  m  14:52:20|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:20|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:20|main  Mining on PoWhash #dcbc6ba3 : 0.00MH/s [A1+0:R0+0:F0]
  m  14:52:20|main  Mining on PoWhash #dcbc6ba3 : 5.14MH/s [A1+0:R0+0:F0]
```

**Comment by searsaw** [comment]
I'm getting the same output. I'm using ethermine pools to mine. I used their documentation that shows how to run `ethminer` with their pooling. I forgot to add export before each of the bash variables in my script. Would this cause this issue. For example, my script to run everything looks like this:

```
GPU_FORCE_64BIT_PTR=0
GPU_MAX_HEAP_SIZE=100
GPU_USE_SYNC_OBJECTS=1
GPU_MAX_ALLOC_PERCENT=100
GPU_SINGLE_ALLOC_PERCENT=100
ethminer --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>
```

**Comment by searsaw** [comment]
@marcofranssen any luck with this?

**Comment by Hukuta** [comment]
> ethminer --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0xf2e831A3e5a1a324a246d9A34eaA51E945D454bc.rig1

> Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

> Please consider a donation to:
> ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

> [OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 2146762752 bytes of GPU memory
  ℹ  14:31:12|ethminer  Connecting to stratum server eu1.ethermine.org:4444
  ℹ  14:31:12|stratum  Connected to stratum server eu1.ethermine.org : 4444
  ℹ  14:31:12|stratum  Starting farm
  ℹ  14:31:12|stratum  Subscribed to stratum server
  ℹ  14:31:12|stratum  Authorized worker 0xf1e831A0e5a1a324a246d9A34eaA51E918D454bc.rig1
  ℹ  14:31:12|stratum  Received new job #91a58ed0
  ℹ  14:31:12|openclminer0  set work; seed: #e586ce62, target:  #0000000112e0
  ℹ  14:31:12|openclminer0  Initialising miner...
  m  14:31:12|ethminer  Mining on PoWhash #91a58ed0 : 0.00MH/s [A0+0:R0+0:F0]
  m  14:31:13|ethminer  Mining on PoWhash #91a58ed0 : 0.00MH/s [A0+0:R0+0:F0]
  m  14:31:13|ethminer  Mining on PoWhash #91a58ed0 : 0.00MH/s [A0+0:R0+0:F0]
  ℹ  14:31:13|stratum  Received new job #a088bdc0
> [OPENCL]:Using platform: NVIDIA CUDA
> [OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
> [OPENCL]:Printing program log
> [OPENCL]:
> 
> [OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
[OPENCL]:clEnqueueNDRangeKernel(-4)
[OPENCL]:clEnqueueNDRangeKernel(-4)

0.00MH/s always

**Comment by 01000101** [comment]
I have the exact same issue (using 1.0.5-cuda or 1.1.6 Windows binaries).

**Comment by soend** [comment]
Having same issue.. cant figure it out.

**Comment by 01000101** [comment]
Try setting the farm recheck to 2000ms+
