### ISSUE TITLE
libjson-rpc-cpp-dev is not a valid package in 15.10+

### ISSUE THREAD

**Issue by frankcash** [Genoil/cpp-ethereum#139]
As the title says.

`libjson-rpc-cpp-dev => libjsonrpccpp-dev`

**Comment by qjflores** [comment]
does this just need to be updated in the readme?

I got the same error with ubuntu  16.04

**Comment by frankcash** [comment]
Yes, the README needs to be updated.  My pull #140 would fix the README.
