### ISSUE TITLE
Compile on Windows

### ISSUE THREAD

**Issue by CreateYourAccount** [Genoil/cpp-ethereum#144]
Build.ethdev.com is no longer available. Please tell me where to download the compiled libraries of cryptopp, curl, leveldb and others, or how to compile from the sources using Visual Studio these required components

**Comment by bbday** [comment]
same here

**Comment by StrongLLC** [comment]
same here

**Comment by CreateYourAccount** [comment]
I found!
https://github.com/ethereum/cpp-dependencies/releases
