### ISSUE TITLE
Can't get started on windows - build.ethdev.com not available

### ISSUE THREAD

**Issue by TimMurnaghan** [Genoil/cpp-ethereum#155]
Without getting some pre-built dependencies we can't build.

C:\cpp-ethereum\extdep>ping build.ethdev.com

Pinging build.ethdev.com [54.88.7.71] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 54.88.7.71:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**Comment by drussilla** [comment]
You can find all dependencies here: 
https://github.com/ethereum/cpp-dependencies/releases/tag/vc120

**Comment by truedat101** [comment]
So do we need a pull request with a fix?  Windows is a legit platform still.

**Comment by truedat101** [comment]
Also, why is this domain offline?

**Comment by truedat101** [comment]
In either case, as this is the work around: 

- fetch the dependencies from that above location manually
- put into some location in your build tree
- unpack the dependencies (untar/gz)

What are the optimal interim steps to reduce the manual setup at this point?  I had to set all of the INCLUDE and LIB variables manually to point to the right locations of these dependencies.  This took awhile.  I'm sure there is another way for the windows build, but would be interested to hear from someone familiar with building on windows?   Also, I tried changing that URL to point to the location provided for the ethereum cpp-depedencies, but the bat script downloader would work properly at that point.

I'm interested in resolving this, however, would like some feedback from someone who has optimized the work around a bit further than I did.

**Comment by TimMurnaghan** [comment]
@truedat101 I agree - but sorry it's probably not me. I did the semi-manual thing too.  I've also ground to a halt as I'm now missing something to do with stratum.  It's pretty clear that this really isn't very close to a "shrink wrap" process.

I found another repo with some batch files in in (I've forgotten where) and it gave me the clue that cmake is a bit of a swiss army knife and that you can install the dependencies into the extdep/install/windows directory using 
cmake -E tar -zxvf <package>-x64.tar.gz
cmake -E copy_directory <package> ..\install\windows

I did get an exe built - but still not quite right for the GPU I was working on.

So yes - some documentation from whoever actually does this would probably be the way forward.
Hopefully including details of where things need to be put. Examples of the build commands would be nice too.

**Comment by truedat101** [comment]
@TimMurnaghan I got mine built, and I'm happy to produce a zipwad if that's useful.  I'm unaware about the stratum issue.   My point is/was that the pulling of dependencies wasn't terribly difficult, just that the cmake process was not as turnkey as the original upstream repository.   I'd be interested in looking at those bat files you have to see if I can rig this together.

**Comment by ajmssc** [comment]
You just put the files in the `download` folder and run getstuff, and it will skip the download part
