### ISSUE TITLE
The variable 'startN' is being used without being initialized

### ISSUE THREAD

**Issue by JohanTh** [Genoil/cpp-ethereum#160]
Hi, I am getting this error when running `.\ethminer -G`:

![minerror](https://cloud.githubusercontent.com/assets/4187434/25781029/8febfd82-3333-11e7-9f27-361fc9191cba.PNG)

**Comment by truedat101** [comment]
I'm seeing the same on Windows 10, this little debugger alert pops up, and in the output, it mining hash rate drops to 0.  If I click abort, obviously it crashes, but if I click ignore, it proceeds, and in fact, resets itself, and then mining seems to work again.

**Comment by truedat101** [comment]
I found where I *think* this error comes up:

https://github.com/Genoil/cpp-ethereum/blob/master/libethcore/EthashCUDAMiner.cpp#L199

I may go into the debugger to check for certain, but clearly this value isn't initialized before it is used.  Set it to 0 at the very least?

**Comment by truedat101** [comment]
Actually, that wasn't where the failure happens, it's in EthStashGPUMinder.cpp:

https://github.com/Genoil/cpp-ethereum/blob/master/libethcore/EthashGPUMiner.cpp#L186

breaks on line 189.  I'll fix this and see if it pops up elsewhere.  Technically, shouldn't we turn on compiler warnings maybe and treat the warnings as bugs, fix those things, and submit this back as a pull request?

**Comment by truedat101** [comment]
@JohanTh did you manage to get your build done easily?  Wondering how you handled the windows dependencies.  The server is down, and I had to grab them manually from the etherium site, and plug them in using the cmake -D flags for each library and variable.

In any case, it looks like you can patch your build by setting startN = 0 in those two places I mention above.  Will see if this works.

**Comment by JohanTh** [comment]
@truedat101 I changed the variable like that but then I gave up on this because it made my computer lag too much. I downloaded the dependencies manually but unfortunately I can't remember what I did with them.

**Comment by truedat101** [comment]
ethminer runs at about 18% of my cpu with 8 cores available.

**Comment by jbrundrett** [comment]
@truedat101 I'm also getting this issue - I tried initializing startN to 0 in both places. Instead of flagging the error, now my GPU just crashes at the same point in computation. This happens in benchmarking or in actually mining, have you found any solution to this?

**Comment by nicklit** [comment]
Also having this issue

**Comment by truedat101** [comment]
What GPUs are you guys running @nicklit and @jbrundrett ?  Most definitely I found that not all GPUs will work with the default opencv implementation.  There are a number of options with running ethminer that may help out with your specific situation.  And did you guys fix the errors in both places where the value is uninitialized?

**Comment by nicklit** [comment]
@truedat101 Running on an NVIDIA GTX 970 with the 382.53 drivers. I tried setting the variables to 0 in both places, and I believe I got passed the error only to find another error. I'm not too familiar with what I am doing. I may mess with it again tonight.

**Comment by truedat101** [comment]
@nicklit my GTX 960 was failing similarly at some point, due to lower memory from what I understand.  Perhaps we can start some additional output (a pastebin) to see where you are failing with the 970.
