### ISSUE TITLE
Invalid shares on linux

### ISSUE THREAD

**Issue by contremaitre** [Genoil/cpp-ethereum#161]
Hello,
I get only invalid shares on linux. Is DAG file always generated on startup, or stored somewhere ?
What's strange is on windows DAG generation takes about 5-10mn but on linux it's less than one minute.

**Comment by Selaron** [comment]
Maybe this is due to incompatible change in libcrypto++, see #105

**Comment by contremaitre** [comment]
Thanks for the answer, I switched from opensuse tumbleweed to kubuntu 17.04 and it's working now
