### ISSUE TITLE
My computer detect a Trojan on the file and delete it

### ISSUE THREAD

**Issue by JustineDesto** [Genoil/cpp-ethereum#162]
Hello,

When I try to open the file I have an error message from my computer saying "Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: Trojan.Gen.NPE"
Then the program is deleted.

Do you have the same problem?
What can I do?

Thank you

Kind regards

**Comment by davidecaminati** [comment]
same problem, i've deleted too

**Comment by ProgrammingPete** [comment]
I believe this is due to hackers creating malicious miner trojans. The antimalware service you have probably thinks its one of those. What file did you try to open?

**Comment by JustineDesto** [comment]
Hello,
The version I downloaded is ethminer-0.9.41-genoil-1.1.7

**Comment by ProgrammingPete** [comment]
I extracted the latest release in the release folder to desktop and it worked fine
