### ISSUE TITLE
0.00MH/s on GeForce GTX 960 (linux Mint)

### ISSUE THREAD

**Issue by Hukuta** [Genoil/cpp-ethereum#164]
Succesfuly build. 

1) with -G

```
./ethminer -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01.rig2

```

> [OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 2088173568 bytes of GPU memory
>   ℹ  17:22:00|ethminer  Connecting to stratum server eu1.ethermine.org:4444
>   ℹ  17:22:00|stratum  Connected to stratum server eu1.ethermine.org : 4444
>   ℹ  17:22:00|stratum  Starting farm
>   ℹ  17:22:00|stratum  Subscribed to stratum server
>   ℹ  17:22:00|stratum  Authorized worker 0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01.rig2
>   ℹ  17:22:00|stratum  Received new job #1937cec5
>   ℹ  17:22:00|openclminer0  set work; seed: #3bd437c4, target:  #0000000112e0
>   ℹ  17:22:00|openclminer0  Initialising miner...
>   m  17:22:02|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:04|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:06|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:08|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
> [OPENCL]:Using platform: NVIDIA CUDA
> [OPENCL]:Using device: GeForce GTX 960(OpenCL 1.2 CUDA)
> [OPENCL]:Printing program log
> [OPENCL]:
> 
> [OPENCL]:Creating cache buffer
> [OPENCL]:Creating DAG buffer
> [OPENCL]:Loading kernels
> [OPENCL]:Writing cache buffer
> [OPENCL]:Creating buffer for header.
> [OPENCL]:Creating mining buffer 0
> [OPENCL]:Creating mining buffer 1
> [OPENCL]:Generating DAG data
> [OPENCL]:clEnqueueNDRangeKernel(-4)
> [OPENCL]:clEnqueueNDRangeKernel(-4)
>   m  17:22:10|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:12|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:14|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:16|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:18|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:20|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:22|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:24|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:26|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:28|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:30|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:22:32|ethminer  Mining on PoWhash #1937cec5 : 0.00MH/s [A0+0:R0+0:F0]
>   ℹ  17:22:33|stratum  Received new job #b8ee13bc

and hang up

2. with cuda:
```
sudo killall ethminer
./ethminer -U -t 1 --farm-recheck 200 -S eu1.ethermine.org:4444 -O 0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01.rig2
```

> [CUDA]:Using grid size 8192, block size 128
> 
>   ℹ  17:24:24|ethminer  Connecting to stratum server eu1.ethermine.org:4444
>   ℹ  17:24:25|stratum  Connected to stratum server eu1.ethermine.org : 4444
>   ℹ  17:24:25|stratum  Starting farm
>   ℹ  17:24:25|stratum  Subscribed to stratum server
>   ℹ  17:24:25|stratum  Authorized worker 0x4bb96091ee9d802ed039c4d1a5f6216f90f81b01.rig2
>   ℹ  17:24:25|stratum  Received new job #525593ca
>   ℹ  17:24:25|cudaminer0  set work; seed: #3bd437c4, target:  #0000000112e0
>   ℹ  17:24:25|cudaminer0  Initialising miner...
>   m  17:24:25|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:25|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:25|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:26|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:26|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:26|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:26|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:26|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:27|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:27|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:27|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:27|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:27|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:28|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:28|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:28|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:28|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:28|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:29|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:29|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:29|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:29|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:29|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:30|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:30|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:30|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:30|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:30|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:31|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:31|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:31|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:31|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:31|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:32|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:32|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:32|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:32|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:32|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:33|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:33|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
>   m  17:24:33|ethminer  Mining on PoWhash #525593ca : 0.00MH/s [A0+0:R0+0:F0]
> Using device: GeForce GTX 960 (Compute 5.2)
> CUDA error in func 'init' at line 243 : out of memory.
> Segmentation fault

Any idea?

**Comment by Smit1237** [comment]
2017-05-12 17:31 GMT+03:00 Odarchenko Nikita <notifications@github.com>:

> CUDA error in func 'init' at line 243 : out of memory.


Obviously - not enough memory to create a dag file

**Comment by Smit1237** [comment]
> [OPENCL]:Found suitable OpenCL device [GeForce GTX 960] with 2088173568 bytes of GPU memory
2 Gb card era is ended, try to mine something else, for ex.  monero or zcash

**Comment by cognizac** [comment]
I'm having the same issue. I successfully built and ran it on Linux Mint 18 (Ubuntu 16.04) with a 960M 4GB (laptop GPU).
I don't understand why it would not enough memory with a regular 960 4GB

**Comment by cognizac** [comment]
Seems my problem was related to trying to run it on multiple GPUs. In my case, I have two 960s and one of them only has 2GB RAM. Maybe that's the problem?

**Comment by s1eight** [comment]
Not sure if this makes a difference, but i think you need to use -U for nvidia cards. Not -G.
