### ISSUE TITLE
CUDA BUILD: : identifier "__CUDA_PREC_DIV" is undefined in device code

### ISSUE THREAD

**Issue by Mazecreator** [Genoil/cpp-ethereum#170]
I have an UBUNTU 16 system and loaded the current repo dependencies.  Upon building, I get an error with __CUDA_PREC_DIV being undefined.  Any way to correct this problem on my end?

> $ make -j8
> [ 10%] Built target ethash
> [ 16%] Built target ethstratum
> [ 59%] Built target devcore
> [ 61%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
> [ 67%] Built target ethash-cl
> [ 67%] Built target BuildInfo.h
> /usr/local/cuda/include/device_functions.hpp(1469): error: identifier "__CUDA_PREC_DIV" is undefined in device code
> 
> 1 error detected in the compilation of "/tmp/tmpxft_00007d8d_00000000-11_ethash_cuda_miner_kernel.cpp3.i".
> CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:266 (message):
>   Error generating file
>   /home/greg/Ethereum/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
> 
> 
> libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:200: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
> make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
> CMakeFiles/Makefile2:320: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
> make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by Mazecreator** [comment]
I modified the .hpp file to remove a few lines (this is around line 1467) of code, updating to look like this:

> __DEVICE_FUNCTIONS_STATIC_DECL__ float fdividef(float a, float b)
> {
> //  if (__USE_FAST_MATH__ && !__CUDA_PREC_DIV) {
>     return __nv_fast_fdividef(a, b);
> //  } else {
> //    return a / b;
> //  }
> }

Although this is not idea, the code did compile.  I will report back if I have problem, but would like help with a more longterm solution, seems like maybe and ENV variable missing from my shell?

**Comment by volpato30** [comment]
May I ask what is your CUDA version? I have the same problem when I tried to compile it with CUDA 8.0. And after I move back to CUDA 7.5 the problem is solved.

**Comment by Mazecreator** [comment]
It is CUDA 8.0, likely the issue.  Somewhere I saw a 7.5 reference as a requirement for this tool but don't remember where I saw it.  I use TensorFlow on the same system and need 8.0.

**Comment by volpato30** [comment]
Interesting, I use Tensorflow in my work too :). You can always install multiple CUDA on a single system. And switching between different CUDA can be done by changing the PATH and LD_LIBRARY_PATH variables. That's my current solution for this problem.

**Comment by Mazecreator** [comment]
Thanks, I may try that.
