### ISSUE TITLE
Shares not being submitted

### ISSUE THREAD

**Issue by movitto** [Genoil/cpp-ethereum#175]
Good day, I'm dual reporting an issue that I'm encountering w/ the genoil cpp-ethereum client. I have commented on the following issue which is similar to mine, but since that is against the old cpp-ethereum project, I figure it'd be best to also to report here

https://github.com/ethereum/webthree-umbrella/issues/361

---
The issue is that while the cpp-ethereum client is not reporting work to various mining pools. This is occurring when mining via a nvidia 1080ti card on linux, and I see various solutions regarding downgrading ATI drivers, but no mention of nvidia.

Official nvidia drivers for linux we successfully installed, and I can see that I'm getting the target hashrate for my card ~30MH/s. While it can successfully connect to  and get work from nanopool, dwarfpool, ethereumpool, and others, no shares are submitted. It just continuously tries to compute the latest job received until the next job is received,

Command:

```
export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100
~/cpp-ethereum/build/ethminer/ethminer --farm-recheck 200 -G -S eth-us-east1.nanopool.org:9999 -O [RETRACTED]
```

example output (addresses have been changed to protect the innocent):

```
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

Please consider a donation to:
ETH: [RETRACTED]
[OPENCL]:Found suitable OpenCL device [GeForce GTX 1080 Ti] with 11715084288 bytes of GPU memory
  ℹ  11:36:37|ethminer  Connecting to stratum server eth-us-east1.nanopool.org:9999
  ℹ  11:36:38|stratum  Connected to stratum server eth-us-east1.nanopool.org : 9999
  ℹ  11:36:38|stratum  Starting farm
  ℹ  11:36:38|stratum  Subscribed to stratum server
  ℹ  11:36:38|stratum  Authorized worker [RETRACTED]
  ℹ  11:36:38|stratum  Received new job #f55c54da
  ℹ  11:36:38|openclminer0  set work; seed: #647f6619, target:  #00000000dbe6
  ℹ  11:36:38|openclminer0  Initialising miner...
  m  11:36:38|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
[More similar output]

[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 1080 Ti(OpenCL 1.2 CUDA)
  m  11:36:40|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
OPENCL#0: 0%
  m  11:36:40|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
OPENCL#0: 1%
OPENCL#0: 2%
OPENCL#0: 2%
  m  11:36:41|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
OPENCL#0: 3%
OPENCL#0: 4%
OPENCL#0: 5%
[More similar output]
OPENCL#0: 97%
  m  11:36:49|ethminer  Mining on PoWhash #f55c54da : 0.00MH/s [A0+0:R0+0:F0]
OPENCL#0: 98%
OPENCL#0: 98%
OPENCL#0: 99%
  m  11:36:49|ethminer  Mining on PoWhash #f55c54da : 10.49MH/s [A0+0:R0+0:F0]
  m  11:36:50|ethminer  Mining on PoWhash #f55c54da : 31.46MH/s [A0+0:R0+0:F0]
  [More similar output]
  ℹ  11:36:56|stratum  Received new job #8cdc1d7d
  ℹ  11:36:56|openclminer0  set work; seed: #647f6619, target:  #00000000dbe6
[Ad inf until I kill the process]
```

I have attempted this over the course of a few days to make sure there are not network issues (the main geth client has been syncing the blockchain fine in that time). Any ideas as to the issue? Is there an easy way to debug exactly whats going on (if the card isn't actually computing the hashes, if they aren't being sent to the sever, if the server isn't accepting them)

Thanks for any help

**Comment by akamaus** [comment]
Confirm, I experience precisely the same problem with Ti1080 and cudatoolkit-8.0.44. Afaik ethminer should report shares it found to console. So probably it's not communication-related issue.

**Comment by Winterlust** [comment]
I'm having trouble too. Ubuntu 16.04, Nvidia p100, cuda 8.0, genoil working properly but no shares are submited.

**Comment by dholm** [comment]
I had the same problem on OSX.  In my case it was because I had cryptopp 5.6.5 installed and I needed to apply this patch:

 https://github.com/Genoil/cpp-ethereum/pull/111

**Comment by akamaus** [comment]
@dholm Wow! That works. Many thanks.

**Comment by movitto** [comment]
@dholm Confirmed, works like a charm! Shares are now being accepted (took several minutes since I just have the one GPU but it's working!)

One caveat on ubuntu, the libcrypto++ package needs to be rebuilt from source as the header required by that patch isn't included in the debian package. See my comment on patch #111 for details.

**Comment by Genoil** [comment]
merged. thanks!
