### ISSUE TITLE
ethminer freezes approx 5 seconds after closing cmd window

### ISSUE THREAD

**Issue by jjisnow** [Genoil/cpp-ethereum#177]
Hi All, 
ethminer has been freezing up/hanging the entire system about 4 seconds after attempting to close it, either by the top right 'x' or the Task Manager on windows 7. 
I have been following this guide off  <https://ethermine.org/>

> "start your miners by putting the following commands into a bat file"

    setx GPU_FORCE_64BIT_PTR 0   
    setx GPU_MAX_HEAP_SIZE 100    
    setx GPU_USE_SYNC_OBJECTS 1   
    setx GPU_MAX_ALLOC_PERCENT 100   
    setx GPU_SINGLE_ALLOC_PERCENT 100   
    ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O <Your_Ethereum_Address>.<RigName>

Has anyone else experienced this and does anyone know a solution?

**Comment by krtschmr** [comment]
i run this and it's not starting but instantly failing without a logfile or something

**Comment by krtschmr** [comment]
replaced -G with -U and it *worked* but not using my GPU

**Comment by jjisnow** [comment]
I've been using the variation with -U and finding it worked but failed on closing. I've also omitted <rig_name> from the address. 
Previously I toyed with reducing --cuda-block-size to 4096 and --syncmode to "yield" but still the same failure.

**Comment by krtschmr** [comment]
@Genoil  why closed? still cant use your mining software....
