### ISSUE TITLE
Mint 18: E: Unable to locate package libjson-rpc-cpp-dev

### ISSUE THREAD

**Issue by wellington1993** [Genoil/cpp-ethereum#179]
Hi,

after try default step by step I got this error:
`E: Unable to locate package libjson-rpc-cpp-dev
`

They have any idea to solve problem and run this software at Linux Mint or latest Ubuntu?

Thanks

**Comment by Winterlust** [comment]
Look at: https://github.com/ethereum/webthree-umbrella/issues/104#issuecomment-170549198

**Comment by wellington1993** [comment]
Thanks @Winterlust !
