### ISSUE TITLE
ethminer+opencl+nvidia = 100% CPU on one thread

### ISSUE THREAD

**Issue by clemtaylor** [Genoil/cpp-ethereum#185]
I just started playing with the opencl ethminer with a gtx1070. I'm getting about 25Mh/s but two CPU threads are running at 100% doing nothing. One thread is spinning calling clock_gettime() [I think from ethash_cl_miner::search()] and the other thread seems like it doing something with nanosleep(). I didn't build with enough debug symbols to figure out more.

It seems this has been an ongoing problem dating back to 2015 (according to google).

I would have tried the cuda miner, but it was failing to build: (cuda SDK 8.0 on Fedora 25)
```
[ 42%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
/usr/local/cuda/include/math_functions.h(8897): error: cannot overload functions distinguished by return type alone
/usr/local/cuda/include/math_functions.h(8901): error: cannot overload functions distinguished by return type alone
```
Before I put any effort into it, is anyone else seeing this problem?

**Comment by akamaus** [comment]
I see one core being fully occupied with ethminer in opencl mode. In cuda mode CPU is free. 

I built cuda-miner from master branch with cuda-7.5, 8.0.47, 8.0.61 on nixos-17.03. Saw no such errors.

**Comment by Genoil** [comment]
I am aware of the issue with OpenCL on Nvidia, but since you can have CUDA, you can avoid it. Getting things built on various *nix flavors is not my specialty.

**Comment by clemtaylor** [comment]
I worked around the compile time problem, it is related to having a version of gcc that is not support by cuda.

Searching for those two line numbers pointed to a workaround, but I just commented them out long enough to get the code to compile.

The nvidia+opencl problem was only actually consuming 100% cpu on one thread (htop was showing thread cpu and a composite CPU usage for the main process).

Except for the 100% cpu issue, there doesn't seem to be much of a difference in performance between the opencl and cuda versions.

**Comment by smasher816** [comment]
I am also having this issue. 100% of one core is being used by the Xorg process after starting ethminer. I have tried both -G (opencl) and -U (cuda) modes.

I am using Arch Linux with:
cuda 8.0.61
ethereum-genoil-git - https://github.com/Genoil/cpp-ethereum/commit/2d692d263f3ba74a3612ad3bbec9e7cfac413a1f
linux 4.11.5

**Comment by noobhacker** [comment]
I can't get GTX970 to run on CUDA mode, it just says all CUDA devices are busy. After some grinding I think it is related to NVIDIA OpenCL busy wait issues.
https://github.com/pandegroup/openmm/issues/1541
