### ISSUE TITLE
Sluggish desktop while mining

### ISSUE THREAD

**Issue by akamaus** [Genoil/cpp-ethereum#187]
I experience serious desktop slowdown while mining both in Cuda and OpenCL modes with my 1080Ti. Switching between tabs, windows, virtual desktops in Kde Plasma is painfully slow. Even web browsing (when scrolling page) is uncomfortable.  Is it expected behavior or some kind of bug?

Software: linux-4.9.30, nvidia-375.66, Cuda-8.0.61, Plasma-5.8.6.

**Comment by Genoil** [comment]
using a lower global work size helps, at the cost of a bit of performance. lower it by dividing the current setting (8192 or 16384?) by 2 until you get decent desktop performance. sometimes you need to go as low as 1024.

**Comment by smasher816** [comment]
Try killing your compositor. Compton gave me 100% cpu usage and full second delays between screen redraws. https://github.com/Genoil/cpp-ethereum/issues/185#issuecomment-308670620

**Comment by akamaus** [comment]
@Genoil, thanks. After some experiments I found the following settings to work best: ```--cuda-grid-size 256 --cuda-block-size 64``` helps indeed. Performance drop is about 5%.
