### ISSUE TITLE
Can't build on Ubuntu 17.04

### ISSUE THREAD

**Issue by ernestp** [Genoil/cpp-ethereum#190]
gcc 4.9

build$ make
-- ctest path: /usr/bin/ctest
 - CryptoPP header: /usr/include
 - CryptoPP lib   : /usr/lib/x86_64-linux-gnu/libcryptopp.so
 - LevelDB header: /usr/include
 - LevelDB lib: /usr/lib/x86_64-linux-gnu/libleveldb.so
 - Jsoncpp header: /usr/include/jsoncpp
 - Jsoncpp lib   : /usr/lib/x86_64-linux-gnu/libjsoncpp.so
 - json-rpc-cpp header: /usr/include
 - json-rpc-cpp lib   : /usr/lib/x86_64-linux-gnu/libjsonrpccpp-common.so;/usr/lib/x86_64-linux-gnu/libjsonrpccpp-server.so;/usr/lib/x86_64-linux-gnu/libjsonrpccpp-client.so
 - microhttpd header: /usr/include
 - microhttpd lib   : /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
 - microhttpd dll   : 
 - readline header: /usr/include
 - readline lib   : /usr/lib/x86_64-linux-gnu/libreadline.so
-- Could NOT find miniupnpc (missing:  MINIUPNPC_INCLUDE_DIR MINIUPNPC_LIBRARY) 
 - gmp header: /usr/include/x86_64-linux-gnu
 - gmp lib   : /usr/lib/x86_64-linux-gnu/libgmp.so
 - curl header: /usr/include/x86_64-linux-gnu
 - curl lib   : /usr/lib/x86_64-linux-gnu/libcurl.so
-- Could NOT find cpuid (missing:  CPUID_INCLUDE_DIR CPUID_LIBRARY) 
 - opencl header: /usr/include
 - opencl lib   : /usr/lib/x86_64-linux-gnu/libOpenCL.so
 - CUDA header: /usr/include
 - CUDA lib   : /usr/lib/x86_64-linux-gnu/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
 - jsonrpcstub location    : ETH_JSON_RPC_STUB-NOTFOUND
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   regex
--   chrono
--   filesystem
--   unit_test_framework
--   program_options
--   random
--   atomic
 - boost header: /usr/include
 - boost lib   : /usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_random.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so
------------------------------------------------------------------------
--                  CMake Version                            3.7.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Linux
-- BUNDLE           Build bundle                             cudaminer
--------------------------------------------------------------- features
--                  Chromium support                         1
--                  Hardware identification support          FALSE
--                  HTTP Request support                     TRUE
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  
-- JSONRPC          JSON-RPC support                         ON
-- OLYMPIC          Default to the Olympic network           OFF
------------------------------------------------------------- components
-- MINER            Build miner                              ON
-- GUI              Build GUI components                     OFF
-- ETHASHCL         Build OpenCL components                  ON
-- ETHASHCUDA       Build CUDA components                    ON
-- ETHSTRATUM       Build Stratum components                 ON
------------------------------------------------------------------------

-- CXXFLAGS: -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Wno-error=parentheses -pedantic -DSHAREDLIB -fPIC  -fuse-ld=gold
creating build info...
createBuildInfo()
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dev/master/build
[  0%] Built target BuildInfo.h
[ 42%] Built target devcore
[ 53%] Built target ethash
[ 59%] Built target ethash-cl
[ 61%] Linking CXX static library libethash-cuda.a
[ 65%] Built target ethash-cuda
[ 71%] Built target ethstratum
[ 73%] Linking CXX shared library libethcore.so
[ 95%] Built target ethcore
[ 97%] Linking CXX executable ethminer
../libstratum/libethstratum.so: error: undefined reference to 'Json::Value::get(std::string const&, Json::Value const&) const'
../libstratum/libethstratum.so: error: undefined reference to 'Json::Reader::getFormattedErrorMessages() const'
../libstratum/libethstratum.so: error: undefined reference to 'Json::Reader::parse(std::string const&, Json::Value&, bool)'
....

**Comment by Feedz** [comment]
also can't build
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 
after:
mkdir build
cd build
cmake -DBUNDLE=miner ..
make -j8

[ 17%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Common.cpp.o
[ 17%] Built target BuildInfo.h
/home/user/Projects/ethereum/cpp-ethereum/libethash/sha3_cryptopp.cpp:25:29: fatal error: cryptopp/keccak.h: No such file or directory
 #include <cryptopp/keccak.h>
                             ^
compilation terminated.
libethash/CMakeFiles/ethash.dir/build.make:134: recipe for target 'libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o' failed
make[2]: *** [libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 19%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonData.cpp.o
[ 21%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonIO.cpp.o
[ 23%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonJS.cpp.o
CMakeFiles/Makefile2:177: recipe for target 'libethash/CMakeFiles/ethash.dir/all' failed
make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FileSystem.cpp.o
[ 28%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FixedHash.cpp.o
[ 30%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Guards.cpp.o
/home/ivan/Projects/ethereum/cpp-ethereum/libstratum/EthStratumClient.cpp: In member function ‘void EthStratumClient::processReponse(Json::Value&)’:
/home/ivan/Projects/ethereum/cpp-ethereum/libstratum/EthStratumClient.cpp:398:12: warning: variable ‘headerHash’ set but not used [-Wunused-but-set-variable]
       h256 headerHash = h256(sHeaderHash);
            ^~~~~~~~~~
/home/ivan/Projects/ethereum/cpp-ethereum/libstratum/EthStratumClientV2.cpp: In member function ‘void EthStratumClientV2::processReponse(Json::Value&)’:
/home/ivan/Projects/ethereum/cpp-ethereum/libstratum/EthStratumClientV2.cpp:350:12: warning: variable ‘headerHash’ set but not used [-Wunused-but-set-variable]
       h256 headerHash = h256(sHeaderHash);
            ^~~~~~~~~~
[ 32%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Hash.cpp.o
[ 34%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Log.cpp.o
[ 36%] Building CXX object libdevcore/CMakeFiles/devcore.dir/MemoryDB.cpp.o
[ 39%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RLP.cpp.o
[ 41%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RangeMask.cpp.o
[ 43%] Building CXX object libdevcore/CMakeFiles/devcore.dir/SHA3.cpp.o
[ 45%] Building CXX object libdevcore/CMakeFiles/devcore.dir/StructuredLogger.cpp.o
[ 47%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o
[ 50%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieCommon.cpp.o
[ 52%] Linking CXX shared library libethstratum.so
[ 52%] Built target ethstratum
[ 54%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieDB.cpp.o
[ 56%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
[ 58%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 60%] Linking CXX shared library libdevcore.so
[ 60%] Built target devcore
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ernestp** [comment]
@Feedz I also had issue with sha3_cryptopp.cpp but solved it with dirty hack:

 #include <cryptopp/sha3.h>
+
+#undef CRYPTOPP_VERSION
+#define CRYPTOPP_VERSION 563
+
 #if (CRYPTOPP_VERSION >= 564)

**Comment by Feedz** [comment]
Thanks, it works now

**Comment by yangfl** [comment]
Also got `../libstratum/libethstratum.so: error: undefined reference to 'Json::Value::get(std::string const&, Json::Value const&) const'` on Debian testing.

**Comment by progone** [comment]
@ernestp 
 I'm looking forward to trying your trick later tonight.  Hopefully it fixes my issue. Thank you

**Comment by pwuertz** [comment]
The "dirty hack" @ernestp suggested makes ethminer compile and it seems to be working, but it will never find or submit solutions. No warning is given whatsoever. I.e. don't use the hack!

The reason/problem for this is described in #111. Due to a change in Cryptopp in 5.6.4 ethminer must use the function defined in `keccak.h`. Since the debian package "forgot" to include this header one has to either copy it from the cryptopp source or update the deb as described in #111.

**Comment by progone** [comment]
I never tried the dirty trick.  

After messing with NVidia's setting and running ` ethminer -G --opencl-platform 1 ` I was able to mine.  However........  
this is the current problem I am dealling with ` ℹ  12:22:45|openclminer0  set work; seed: #3868abc5, target:  #000000000000`
