### ISSUE TITLE
GTX 970 Performance Level being lowered when ethminer starts?

### ISSUE THREAD

**Issue by KillerKelvUK** [Genoil/cpp-ethereum#193]
Hi, thanks for a great tool, I saw a humongous improvement using your ethminer fork vs. ethereum's oob so your work is most certainly appreciated, thank you.  If you wouldn't mind I have a small query regards how ethminer could be affecting my gtx overclock setup...

I'm running Ubuntu 16.04 and a cold boot see's my GTX start off at performance level 3, this level is required to unlock the graphics and memory overclock offsets under the nvidia-375 drivers (coolbits needed as well).  This performance level remains **until** I start ethminer where it drops to 2.  This behaviour is only with ethminer i.e. a comparable test on cold boot but with heaven benchmark does not change the nvidia performance level setting.

I can manually increase the performance level after starting ethminer by using the nvidia-smi tool and adjusting the application clocks (-ac) back to their highest pairing which in turn increases the performance level and unlocks the overclock offsets.

Is this behaviour expected/known or do I have a bodged config somewhere (using Cuda 8.0)?  By forcing performance level 3 and setting my graphics clock offset to +250 I get a nice 5+MH/s addition taking me to 20+MH/s which reading around seems right for this gpu.  The only niggle is that the nvidia-smi tool requires root privileges for changing the application clocks which makes scripting this for reboots awkward.

I run ethminer with -U (-G isn't as performant) and no other application parameters.

Is there anything you can recommend?

**Comment by JHGitty** [comment]
Hi, i have the same issue here under Ubuntu 16.04. I have the same issue with GTX 1060 (6GB) and GTX 980 Ti. I think this issue is related to the code of this miner.

1. Did you try other miners? Do they also have the issue?
2. Can you write here the nvidia-smi workaround to help users in the meanwhile? I think it will take a long time until it will be officially fixed.

**Comment by KillerKelvUK** [comment]
@JHGitty, I'm new to mining so haven't tested any other mining tool to compare other than ccp-ethereum from the ethereum repo, I tend to stick with open source projects so Claymore is probably not something I'll bother with, same goes for ethOS.

I'm using the stock ubuntu nvidia-375 package for the driver and then installed CUDA 8 via the network (apt) option by downloading the deb directly from nvidia.

I have a bash script which applies the GPU changes I want (see below).  The "nvidia-smi -ac" command for me needs to be run with root privileges (aka sudo) I suspect you will require the same.  The other commands shown below then apply the additional overclocks...

```
#!/bin/bash
/usr/bin/sudo /usr/bin/nvidia-smi -ac 3505,1455
/usr/bin/nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1
/usr/bin/nvidia-settings -a [gpu:0]/GPUGraphicsClockOffset[3]=200
```

**Comment by Maximilian-Reuter** [comment]
at least on windows you can use the cmdline option "-acp 0" to be able to change the clocks without admin privileges

**Comment by KillerKelvUK** [comment]
@Maximilian-Reuter yes the same option is valid for linux but that command itself requires root privileges to execute and isn't persisted between reboots so same issue but from a different direction.

```
   -acp, --applications-clocks-permission=MODE
       Toggle whether applications clocks can be changed by all  users  or  only  by  root.
       Available  arguments  are  0|UNRESTRICTED, 1|RESTRICTED.  For Tesla devices from the
       Kepler+ family and Maxwell-based GeForce Titan.  Requires root.
```
