### ISSUE TITLE
symbol lookup error: /usr/lib/x86_64-linux-gnu/libethstratum.so: undefined symbol: _ZN4Json6Reader5parseERKSsRNS_5ValueEb

### ISSUE THREAD

**Issue by LinuxETC** [Genoil/cpp-ethereum#196]
Greetings.

I am using "ethminer-0.9.41-genoil-1.1.7" via KopiemTu (on Ubuntu 16.04 in short) with some NVIDIA 750Ti (x6).   When using the following from the command line

`ethminer -G -S coinotron.com:3344 -O _user_._worker_:_password_`

I receive the following error message:

`/opt/miners/ethminer-0.9.41-genoil-1.1.7/ethminer: symbol lookup error: /usr/lib/x86_64-linux-gnu/libethstratum.so: undefined symbol: _ZN4Json6Reader5parseERKSsRNS_5ValueEb`

Questions and feedback are welcomed.  Thanks in advance.

**Comment by lifespirit** [comment]
So... I think you have same problem: https://github.com/Genoil/cpp-ethereum/issues/199
