### ISSUE TITLE
OpenCL 1.2 causes low performance in GTX970

### ISSUE THREAD

**Issue by noobhacker** [Genoil/cpp-ethereum#197]
On GTX970 using CUDA isn't working, have to use openCL. 
Most people suggest to run 347.88, for some reason I couldn't run it daily. After some grinding I found that when using the old driver it uses **OpenCL 1.1**, while new driver using OpenCL 1.2, the results (mh/s) for 1.1 is like 19, 20, 19, 20 and for 1.2 is like 0, 4, 5, 0, 0, 4, 5. I wonder is there anyway to force it to run as OpenCL 1.1 without downgrading drivers? Thanks for your awesome work!

**Comment by tengg** [comment]
Have you found a solution yet?

**Comment by noobhacker** [comment]
No relation with OpenCL version, a thread on reddit says need to enable Optimize for Compute Performance in nvidia settings (latest drivers).
