### ISSUE TITLE
Slower Mining than on Wndows 10

### ISSUE THREAD

**Issue by lohmag** [Genoil/cpp-ethereum#198]
I compile ethminer under Ubuntu server 16.04 using the latest CUDA library - "cuda_8.0.61_375.26_linux-run" using the same driver as cuda version 375.26. It's working by showing only ~26MH/s on GTX 1070.
On Windows it mining at ~31MH/s
Is there anything I can do to speed up?

**Comment by s1eight** [comment]
You can research how to overclock your gpu. Use Nvidia x server settings.
Try +200 graphics clock, +1500 memory transfer rate.
