### ISSUE TITLE
ethminer: symbol lookup error: ethminer: undefined symbol: _ZN3dev3eth15EthashCUDAMiner14s_numInstancesE

### ISSUE THREAD

**Issue by lifespirit** [Genoil/cpp-ethereum#199]
System: Linux pve 4.4.62-1-pve #1 SMP PVE 4.4.62-88 (Thu, 18 May 2017 09:18:43 +0200) x86_64 GNU/Linux (Debian Jessie REPO)

cmake: cmake version 3.8.2
Cuda version: cuda_8.0.61_375.26

compile:
cmake -DBUNDLE=cudaminer -DCMAKE_INSTALL_PREFIX=/ ..
make OPENCL_HEADERS=/usr/local/cuda-8.0/targets/x86_64-linux/include LIBOPENCL=/usr/local/cuda-8.0/targets/x86_64-linux/lib -j8

Have error:
ethminer: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by ethminer)
ethminer: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /usr/lib/libethash-cl.so)
ethminer: symbol lookup error: ethminer: undefined symbol: _ZN3dev3eth15EthashCUDAMiner14s_numInstancesE

I have no idea how fix this. =( May  be some lib to old or to new? (\/_\/)

**Comment by lifespirit** [comment]
Some more information:
# ldd /bin/ethminer
/bin/ethminer: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /bin/ethminer)
/bin/ethminer: /usr/local/cuda-8.0/lib64/libOpenCL.so.1: no version information available (required by /lib/libethash-cl.so)
I think ethminer can't link cuda libraries.

**Comment by s1eight** [comment]
I dont think anything is wrong with ethminer, there are plenty of people
who seem to be able to get the software to work. You might need to
uninstall your drivers and reinstall. Make sure you uninstall any old
versions, could be a conflict.

**Comment by lifespirit** [comment]
I have only 1 installed CUDA + drivers. I install it from NVIDIA binaries. Now I try reinstall, but it don't work. =( Compilation successed, but binary file can't load libOpenCL.so.1 =(

**Comment by lifespirit** [comment]
So... Resolved.
Symptoms:
ldd /etc/ethminer show that can't load libOpenCL.so

Result:
1. In first I build newest cmake. It resolve many problems before libs error.
2. Nvidia recomended link to /usr/local/cuda/lib64 in /etc/ld.conf.d/cuda.conf
So... This bad idea. I do that:
Commented all in /etc/ld.so.conf.d/cuda.conf
Commented all in /etc/ld.so.conf.d/x86_64-linux-gnu.conf
reload config:

ldconfig -f /etc/ld.so.conf

Now ldconf look like that:

ldconfig -v | grep ":"

/sbin/ldconfig.real: /lib/x86_64-linux-gnu/ld-2.19.so is the dynamic linker, ignoring

/usr/lib/x86_64-linux-gnu/libfakeroot:
/usr/local/lib:
/lib/x86_64-linux-gnu:
/usr/lib/x86_64-linux-gnu:
/lib:
/usr/lib:
/usr/lib/x86_64-linux-gnu/tls: (hwcap: 0x8000000000000000)

And my PATH look like that:
# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda/bin

I create symlinks to all libs from /usr/local/cuda/lib64 to /lib64
cd /usr/local/cuda/lib64
for i in `ls`; do ln -s /usr/local/cuda/lib64/$i /lib64/; done

Then I checked that system linked libOpenCL.so.1 to /lib64/ directory
whereis libOpenCL.so.1.0
libOpenCL.so.1: /lib64/libOpenCL.so.1.0 /lib64/libOpenCL.so.1

Then I compile ethminer with this params:
cmake -DBUNDLE=cudaminer -DCOMPUTE=61 -DCMAKE_INSTALL_PREFIX=/ ..
make OPENCL_HEADERS=/usr/local/cuda/include/ LIBOPENCL=/lib64/ -j8

Check maked bin file
ldd ethminer/ethminer

All libs must work. =)
So... This is realy hard way. ^_^
