### ISSUE TITLE
--opencl-device <n> broken in 1.0.6

### ISSUE THREAD

**Issue by Genoil** [Genoil/cpp-ethereum#20]
always picks device 0

**Comment by Fossius** [comment]
Hi. When will be fixed?

**Comment by Equinox-** [comment]
Strangely the `--opencl-devices` option seems to work.  This seems indicative of the `--opencl-device` using old code that wasn't removed when the `--opencl-devices` option was added.

**Comment by Genoil** [comment]
should be fixed with https://github.com/Genoil/cpp-ethereum/commit/59e88801cad40e0083393684d4db8dfa12d5ad69
