### ISSUE TITLE
Ubuntu 14.04 w/ NVIDIA CUDA 8.0.61 unable to build

### ISSUE THREAD

**Issue by mknippen** [Genoil/cpp-ethereum#202]
Followed the following instructions:

> sudo dpkg -i cuda-repo-ubuntu1404_7.5-18_amd64.deb
```
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get update
sudo apt-get install git cmake libcryptopp-dev libleveldb-dev libjsoncpp-dev libjson-rpc-cpp-dev libboost-all-dev libgmp-dev libreadline-dev libcurl4-gnutls-dev ocl-icd-libopencl1 opencl-headers mesa-common-dev libmicrohttpd-dev build-essential cuda -y
git clone https://github.com/Genoil/cpp-ethereum/
cd cpp-ethereum/
mkdir build
cd build
cmake -DBUNDLE=cudaminer ..
make -j8
```
Result:

```
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_000009ff_00000000-17_ethash_cuda_miner_kernel.compute_61.cpp1.ii".
Compilation terminated.
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:264 (message):
  Error generating file
  /home/ubuntu/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make: *** [all] Error 2
```

Output of NVIDIA Version:
```
ubuntu@TestRig:~/cpp-ethereum/build$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
Installed by run command and NVIDIA driver. I'm able to run CUDA samples without issue.

**Comment by mknippen** [comment]
Building the OpenCL version `cmake -DBUNDLE=miner ..` works without issue

**Comment by s1eight** [comment]
So just curious, you were able to compile by changing cudaminer to miner? Am I reading your notes correctly?

**Comment by mknippen** [comment]
Yes, that is correct. However, I was not able to use the CUDA miner, which would be much more performant.

**Comment by s1eight** [comment]
Dumb question, but are you sure you downloaded the correct CUDA software? The notes on the front page of this github, are outdated they still reference CUDA7.

**Comment by mknippen** [comment]
Yes, I’m at the latest version of the CUDA software. The driver and kernel match, and I’m able to run sample code without issue.

**Comment by progone** [comment]
arggg

~/cpp-ethereum/build$ cmake -DBUNDLE=miner ..
CMake Error: The source "/home/matthew/cpp-ethereum/CMakeLists.txt" does not match the source "/home/matthew/cpp-ethereum/build/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

**Comment by vyarmak** [comment]
Had same problem. Seems to be that problem is in `libethash-cuda/CMakeLists.txt`. More detailed - here https://github.com/Genoil/cpp-ethereum/commit/0b1da6b545198078d1bbe9278c3099add785237d

You need to change 
```
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};--disable-warnings;--ptxas-options=-v;-use_fast_math;-lineinfo)
``` 

for

```
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};--std=c++11;--disable-warnings;--ptxas-options=-v;-use_fast_math;-lineinfo)
```
