### ISSUE TITLE
minor build warning

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#21]
Successfully built ethminer 0.9.41-genoil-1.0.6 with gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4, but a minor build error was reported:

[100%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
In file included from /root/cpp-ethereum/ethminer/main.cpp:39:0:
/root/cpp-ethereum/ethminer/MinerAux.h: In member function ‘void MinerCLI::doFarm(dev::eth::MinerType, std::string&, unsigned int)’:
/root/cpp-ethereum/ethminer/MinerAux.h:872:9: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
      if (current.seedHash != newSeedHash)
         ^

**Comment by Genoil** [comment]
fixed with https://github.com/Genoil/cpp-ethereum/commit/63acddf812af0cc09e23652cb622c6b509038262
