### ISSUE TITLE
Issues getting started.

### ISSUE THREAD

**Issue by Phaceial** [Genoil/cpp-ethereum#210]
I've been working at this for 4 hours now, so it's safe to say I need help. I was having issues at first but that's because I didnt make Cmake the default on all profiles, That's been fixed. I finally had a solution built, but everytime I would load it in Visual Studio 17, Nothing would happen. I was also unable to open ethminer.exe.  So I deleted everything and decided to try the method that was on this website. I open getstuff and nothing happens. When I try to use Cmake to make a solution I get the following

 - WindowsSDK dirs: C:/Program Files (x86)/Windows Kits/8.1;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.0A;C:/Program Files (x86)/Windows Kits/8.0;C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A
ctest path: C:/Program Files/CMake/bin/ctest.exe
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP (missing: CRYPTOPP_INCLUDE_DIR CRYPTOPP_LIBRARY)
  (Required is at least version "5.6.2")
Call Stack (most recent call first):
  cmake/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCryptoPP.cmake:107 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/EthDependencies.cmake:44 (find_package)
  CMakeLists.txt:246 (include)

Any help would be appreciated. I'm calling it a night though.

**Comment by nicklit** [comment]
I believe this is related to the bat file not working because ethdev.com is down or gone, and cryptoPP isn't downloading for you. #183 may help you some, but I'm having still having issues also. At least that may help you get cryptoPP and some other packages downloaded

**Comment by Phaceial** [comment]
Thanks I saw that this morning, looking to try when I get home.

**Comment by abdullaqeblawi** [comment]
I am also having the same issue. Has anyone been able to compile on windows successfully?

**Comment by nicklit** [comment]
Initially I did not realize there was a stable version in the releases folder. Instead of building it from pulling it down, I was able to get the version 1.1.7 to work without issues. Hopefully that helps anyone who was also confused like I was

**Comment by abdqeb** [comment]
That version is from last year I think. I was hoping for a recent version with the update for 1060 GTX cards
