### ISSUE TITLE
OpenCL 1.2 on macOS runs oddly slow

### ISSUE THREAD

**Issue by tengg** [Genoil/cpp-ethereum#212]
My card is Radeon HD 7950, from the online sources, it should run the hash rate around 10-20 at least.

But on my Mac, it runs only at 3MH/s..
My another card, GTX 1070, running at 25MH/s with cuda, but same 3MH/s with OpenCL1.2..

**Comment by juanvisoler** [comment]
Little off topic but regarding the GTX 1070 I am getting 31.4MH/s with +966 MHz memory overclock on Windows 10.
