### ISSUE TITLE
Stuck at "OPENCL#0: 99%"

### ISSUE THREAD

**Issue by notjoe** [Genoil/cpp-ethereum#216]
I am running ubuntu 16.04.1 with kernel 4.8.0-54-generic. When i start the mining client it gets stuck at "OPENCL#0: 99%" and just hangs there. I have the latest AMDGPU drivers for a R9 290x GPU.

00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port (rev 09)
00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
00:16.0 Communication controller: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 (rev c4)
00:1c.3 PCI bridge: Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 4 (rev c4)
00:1d.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation H77 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii XT [Radeon R9 290X]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Hawaii HDMI Audio
02:00.0 Network controller: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)

**Comment by nikolehto** [comment]
I have same problem, but also my computer does freeze totally. The release binary for Windows does work, but if I build with Visual Studio for windows, or with make for Ubuntu, the program runs till OPENCL#0: 99% ( or 98% sometimes) and then it cames unstable. 

On Windows : console freezes and after that screen goes black. Sometimes it recovers and sometimes it corrupt windows or something and I have to make multiple reboots for computer to make Windows repair itself

On Ubuntu : All freezes on 99%, only thing what I can do is restart. 

On windows I did use VS2015 with vs120-tools, and found libraries from cpp-ethereum git. On ubuntu I followed instructions carefully

On windows I even tried to build older branch (c2245a954e8e7938edcb551f39a07695c942b83d) but still it does the same.

Operating System: Windows 10 and Ubuntu 16.04
GPU Driver:  Radeon 17.1.1 on windows and amdgpu-pro-17.10 on ubuntu.

I also noticed that output of self-builded and pre-builded programs differs..

[SelfBuilded Windows.txt](https://github.com/Genoil/cpp-ethereum/files/1087892/SelfBuilded.Windows.txt)
[PreBuilded 1.17 Windows.txt](https://github.com/Genoil/cpp-ethereum/files/1087891/PreBuilded.1.17.Windows.txt)

**Comment by gsedej** [comment]
I have the same issue.
Ubuntu 16.04.2, kernel 4.4, RX 480.
Driver amdgpu-pro 17.10 and 16.06 (not sure, the last of 16.x). All the same. when reaching 98%, totally freeze...


It works on with `ROCm` (work in progress open source driver from AMD). Install instructions for ubuntu: https://github.com/RadeonOpenCompute/ROCm

It is somehow "slow". I only get ~19MH/s but the number stays the same if i manually underclock from to 900MHz (from max 1300MHz) - it makes much heat/noise/power_consumption
```
sudo su
echo manual > /sys/class/drm/card0/device/power_dpm_force_performance_level
echo 2 > /sys/class/drm/card0/device/pp_dpm_sclk
cat /sys/class/drm/card0/device/pp_dpm_sclk
```

**Comment by nikolehto** [comment]
Sounds nice, but my cpu is not compatible. Tried install latest 17.6.2 drivers on windows - did not help.

**Comment by nikolehto** [comment]
I got it working on Ubuntu. I had to downgrade the OpenCL ICD to version 16.40. The answer was already in #141

No kernel or driver downgrades needed just 

Download the 16.40 driver http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx
Extract the driver archive with 

```
tar xvJf amdgpu-pro-16.40-348864.tar.xz
cd amdgpu-pro-16.40-348864
dpkg -i opencl-amdgpu-pro-icd_16.40-348864_*.deb

echo "opencl-amdgpu-pro-icd hold" | sudo dpkg --set-selections
echo "opencl-amdgpu-pro-icd:i386 hold" | sudo dpkg --set-selections
```

from:
https://github.com/genesismining/sgminer-gm/wiki/Compile-sgminer-5.5.5-in-Ubuntu-16.04.1-LTS#212-amd-linux-graphics-driver-amdgpu-pro

**Comment by gsedej** [comment]
Great! It does work! Has anyone tried installing this with opensource amdgpu (non"-pro") that comes with ubuntu?

**Comment by cameronhr** [comment]
Still not working, any thoughts?

OS: Ubuntu 16.04.2 w/ kernel 4.8.0-59-generic 
Installed amdgpu-pro 17.10, then overwrote the OpenCL ICD with 16.40 per above.
R9 290 4GB

I also tried adding the Padoka PPA. This resulted in endless "Mining on PoWhash #xxxxxxx : 0.00MH/s..."
This would end in "stratum Read response railed: End of File"
Then begin hashing again

Maybe I should just do a clean install with 14.04 and use fglrx?

**Comment by kusayuzayushko** [comment]
ok, it works somehow in benchmark mode with OpenCL from amdgpu-pro 16.40, without any kernel o driver downgrade, but hashrate is so low, it's a joke. And i have no luck with actual mining on a pool.

**Comment by RyanF109** [comment]
This fixed my issue with high hashrate:
https://github.com/genesismining/sgminer-gm/wiki/Compile-sgminer-5.5.5-in-Ubuntu-16.04.1-LTS#212-amd-linux-graphics-driver-amdgpu-pro
