### ISSUE TITLE
Ubuntu 17 Can't Build - Fails at 67%

### ISSUE THREAD

**Issue by jasonvds** [Genoil/cpp-ethereum#217]
Disclaimer - I'm reasonably inexperienced at building on Linux. Really struggling after a few hours to get this to work. Any help would be greatly appreciated!

si@ryzen1:~/cpp-ethereum/build$ cmake -DBUNDLE=cudaminer ..*** WARNING: -DHEADLESS=1 option is DEPRECATED! Use -DBUNDLE=minimal or -DGUI=0
-- ctest path: /usr/bin/ctest
 - CryptoPP header: /usr/include
 - CryptoPP lib   : /usr/lib/x86_64-linux-gnu/libcryptopp.so
 - LevelDB header: /usr/include
 - LevelDB lib: /usr/lib/x86_64-linux-gnu/libleveldb.so
 - Jsoncpp header: /usr/include/jsoncpp
 - Jsoncpp lib   : /usr/lib/x86_64-linux-gnu/libjsoncpp.so
 - json-rpc-cpp header: /usr/include
 - json-rpc-cpp lib   : /usr/lib/x86_64-linux-gnu/libjsonrpccpp-common.so;/usr/lib/x86_64-linux-gnu/libjsonrpccpp-server.so;/usr/lib/x86_64-linux-gnu/libjsonrpccpp-client.so
 - microhttpd header: /usr/include
 - microhttpd lib   : /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
 - microhttpd dll   : 
 - readline header: /usr/include
 - readline lib   : /usr/lib/x86_64-linux-gnu/libreadline.so
-- Could NOT find miniupnpc (missing:  MINIUPNPC_INCLUDE_DIR MINIUPNPC_LIBRARY) 
 - gmp header: /usr/include/x86_64-linux-gnu
 - gmp lib   : /usr/lib/x86_64-linux-gnu/libgmp.so
 - curl header: /usr/include/x86_64-linux-gnu
 - curl lib   : /usr/lib/x86_64-linux-gnu/libcurl.so
-- Could NOT find cpuid (missing:  CPUID_INCLUDE_DIR CPUID_LIBRARY) 
-- Could NOT find OpenCL (missing:  OpenCL_INCLUDE_DIR) 
 - CUDA header: /usr/local/cuda/include
 - CUDA lib   : /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
 - jsonrpcstub location    : ETH_JSON_RPC_STUB-NOTFOUND
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.7/Modules/FindBoost.cmake:1470 (_Boost_MISSING_DEPENDENCIES)
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  cmake/EthDependencies.cmake:190 (find_package)
  CMakeLists.txt:246 (include)

 - boost header: Boost_INCLUDE_DIR-NOTFOUND
 - boost lib   : 
------------------------------------------------------------------------
--                  CMake Version                            3.7.2
-- CMAKE_BUILD_TYPE Build type                               Release
-- TARGET_PLATFORM  Target platform                          Linux
-- BUNDLE           Build bundle                             cudaminer
--------------------------------------------------------------- features
--                  Chromium support                         1
--                  Hardware identification support          FALSE
--                  HTTP Request support                     TRUE
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  
-- JSONRPC          JSON-RPC support                         ON
-- OLYMPIC          Default to the Olympic network           OFF
------------------------------------------------------------- components
-- MINER            Build miner                              OFF
-- GUI              Build GUI components                     OFF
-- ETHASHCL         Build OpenCL components                  OFF
-- ETHASHCUDA       Build CUDA components                    ON
-- ETHSTRATUM       Build Stratum components                 ON
------------------------------------------------------------------------

-- CXXFLAGS: -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Wno-error=parentheses -pedantic -DSHAREDLIB -fPIC  -fuse-ld=gold
creating build info...
createBuildInfo()
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libdevcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/libethcore
   used as include directory in directory /home/si/cpp-ethereum/ethminer
   used as include directory in directory /home/si/cpp-ethereum/ethminer
   used as include directory in directory /home/si/cpp-ethereum/ethminer
   used as include directory in directory /home/si/cpp-ethereum/ethminer
   used as include directory in directory /home/si/cpp-ethereum/ethminer
   used as include directory in directory /home/si/cpp-ethereum/ethminer
   used as include directory in directory /home/si/cpp-ethereum/ethminer

-- Configuring incomplete, errors occurred!
See also "/home/si/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
See also "/home/si/cpp-ethereum/build/CMakeFiles/CMakeError.log".

**Comment by jasonvds** [comment]
Managed to build with dependencies, but now failing on make -j8 as below:

~/cpp-ethereum/build$ make -j8
[  2%] Building CXX object libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o
[  8%] Built target ethstratum
[ 51%] Built target devcore
[ 51%] Built target BuildInfo.h
/home/si/cpp-ethereum/libethash/sha3_cryptopp.cpp:25:29: fatal error: cryptopp/keccak.h: No such file or directory
 #include <cryptopp/keccak.h>
                             ^
compilation terminated.
libethash/CMakeFiles/ethash.dir/build.make:134: recipe for target 'libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o' failed
make[2]: *** [libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o] Error 1
CMakeFiles/Makefile2:177: recipe for target 'libethash/CMakeFiles/ethash.dir/all' failed
make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jasonvds** [comment]
Made it a little further:
[ 59%] Built target ethstratum
[ 61%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieDB.cpp.o
[ 63%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
[ 65%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 67%] Linking CXX shared library libdevcore.so
[ 67%] Built target devcore
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jasonvds** [comment]
Bottomed out:

[ 61%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
[ 67%] Built target ethash-cl
[ 67%] Built target BuildInfo.h
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /usr/local/cuda/include/cuda_runtime.h:78:0,
                 from <command-line>:0:
/usr/local/cuda/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.Release.cmake:222 (message):
  Error generating
  /home/softiron/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:320: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by echorebel** [comment]
ubuntu 17 ships with gcc 6. try install gcc-5
then add 
```
SET(CMAKE_C_COMPILER /usr/bin/gcc-5)
SET(CMAKE_CXX_COMPILER /usr/bin/gcc-5)
``` 
to CMakeList.txt. It will now do more but still failing on some undefined reference to std and boost libs.
Maybe it's working on your end or someone knows how to resolve the undefined references.

**Comment by papaiatis** [comment]
@jasonvds would have been nice if you also post your solutions for each issue.
I'm stuck at the cryptopp/keccak.h "No such file or directory"

@echorebel which CMakeLists.txt? The one located in the root of cpp-ethereum? If so, where should I put those two lines exactly?

Need more details!

**Comment by GoSpud** [comment]
Does anyone know how to get past this yet...libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:320: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
