### ISSUE TITLE
How mining without using pool? Where can I see ETH generated?

### ISSUE THREAD

**Issue by stuart1975** [Genoil/cpp-ethereum#221]
Hello,
where I can find a good tutorial to start mining without using a pool.

I am trying this command in windows command shell but not sure if it is correct.

ethminer.exe -G --opencl-platform 0 -O 0x<my account address>/<email> 

Where can I see any progress of mining (ETH generated)? 
See only in command shell process going on but do not see where my ETH generated will go.

Best Regards

**Comment by a0s** [comment]
@stuart1975 You should use "geth --rpc" as local pool - https://github.com/ethereum/go-ethereum
Before it, create you wallet with "geth console" and then waiting end of synchronisation with "geth --rpc"
