### ISSUE TITLE
[CentOS] Physically can't build Ethminer

### ISSUE THREAD

**Issue by omento** [Genoil/cpp-ethereum#222]
I've been trying for the past few hours using this repo and some of the pull requests, but I cannot find a way to `make` Ethminer without failing.

I'm running with CentOS 7:
  - GCC 4.8.5
  - CMake 2.8.12
  - CUDA 8.0 (for GTX 1070)

When I run `cmake -DBUNDLE=cudaminer ..` I get the following warning but it finishes fine.
```
CMake Warning at libethcore/CMakeLists.txt:21 (add_library):
  Cannot generate a safe runtime search path for target ethcore because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libOpenCL.so.1] in /usr/lib64 may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at ethminer/CMakeLists.txt:22 (add_executable):
  Cannot generate a safe runtime search path for target ethminer because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libOpenCL.so.1] in /usr/lib64 may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
```

When I run `make` however is when things go nuts. I've attached the error's in a file, along with the CMAKE Error log and Output as they are quite lengthy.

I have also tried with `-DCOMPUTE=61` and `-DETHASHCL=0` with no luck.

[make.txt](https://github.com/Genoil/cpp-ethereum/files/1083229/make.txt)
[CMakeError.log.txt](https://github.com/Genoil/cpp-ethereum/files/1083230/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/Genoil/cpp-ethereum/files/1083231/CMakeOutput.log.txt)

**Comment by savskii** [comment]
Hi, backup then delete libOpenCL.so.1 from /usr/local/cuda/lib64 
then run cmake -DBUNDLE=cudaminer -DCOMPUTE=61 .. 

Im no expert but try that... getting this to work is hard work and after all that i can't even see any difference in hash speed or power using between OpenCL and Cuda.. unless im doing something wrong

**Comment by omento** [comment]
Thanks @savskii , but I ended up doing another thing. I installed the devtoolset-4 collection which gives me GCC 5.3.x, and I was able to get through compiling when using cmake3. Unfortunately, I couldn't run the binary due to it searching for libssl.so.1 which doesn't exist. I have libssl.so.1.0.1e but symlinking to the correct name doesn't work unfortunately. I'm okay with this, this was more of a practice in compiling tools and familiarizing myself with CMAKE. I've been able to successfully compile other mining tools for Monero with little issue since getting ahold of newer GCC versions.

**Comment by omento** [comment]
After symlinking `libssl.so.1.0.1e` <-> `libssl.so.1.0.0` and `libcrypto.so.1.0.1e` <-> `libcrypto.so.1.0.0` everything works fine, OpenCL and CUDA. I would like to note however that CMAKE can't find the libraries for `cpuid` and `miniupnpc` despite having them installed. CMAKE3 has no issues with the multiple OpenCL libraries, but CMAKE2 will say there's potential errors.
