### ISSUE TITLE
[error message] Read response failed: The semaphore timeout period has expired

### ISSUE THREAD

**Issue by verybigfurrymonster** [Genoil/cpp-ethereum#224]
Hi,
I m using ethminer-0.9.41-genoil 1.1.17 and I can t get it to work.
I get the " Read response failed: The semaphore timeout period has expired" error in a loop.
My setup works with claymore so I m wondering what s wrong with my genoil config.
I also tried OPENCL but same error

ethminer.exe --farm-recheck 1000 -U -S eth-us-west1.nanopool.org:9999 -FS eth-eu2.nanopool.org:9999 -O <mywallet>

Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Using grid size 8192, block size 128

  i  11:05:42|main  Connecting to stratum server eth-us-west1.nanopool.org:9999
  i  11:05:42|stratum  Connected to stratum server eth-us-west1.nanopool.org : 9999
  i  11:05:42|stratum  Starting farm
  X  11:06:15|stratum  Read response failed: The semaphore timeout period has expired
  i  11:06:15|stratum  Reconnecting in 3 seconds...
  i  11:06:18|stratum  Connecting to stratum server eth-us-west1.nanopool.org:9999
  i  11:06:18|stratum  Connected to stratum server eth-us-west1.nanopool.org : 9999

**Comment by vggtd** [comment]
I was receiving the semaphore error message.  After hours of scouring through settings, my Asus RT-AC68R router has an option for "vulnerability protection." As soon as I turned this option off the pool mining started. I hope this information helps someone else.
