### ISSUE TITLE
getstuff bat file not working for windows

### ISSUE THREAD

**Issue by arfeenm** [Genoil/cpp-ethereum#227]
Seems like the getstuff.bat file isnt working on windows.

I was debugging and found the link no longer works: https://build.ethdev.com/builds/windows-precompiled 

Also, this causes my install to fail because it is not able to find the cryptopp stuff this link is suppose to download.

**Comment by someguy111** [comment]
Same issue here. Server temporarily down?

ERROR CODE:    0x80072ee2 - The operation timed out
ERROR CONTEXT: 0x00000005 - The error occurred while the remote file was being processed.

**Comment by emocanu** [comment]
See https://github.com/Genoil/cpp-ethereum/issues/183
