### ISSUE TITLE
issue with cmake -DBUNDLE=cudaminer -G "Visual Studio 12 2013 Win64" ..

### ISSUE THREAD

**Issue by wilku103** [Genoil/cpp-ethereum#229]
when i write cmake -DBUNDLE=cudaminer -G "Visual Studio 12 2013 Win64" .. in cmd its getting error

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:9 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:9 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!

**Comment by nikolehto** [comment]
Are you running visual studio 2013? If yes you have no compile tools, you can download the by creating empty c++ project. If not you need to install v120 toolset. Just modify Visual Studio install and select Windows 8.1 and Windows Phone 8.0/8.1 Tools. Or alternatively you can install Visual Studio 2013....

**Comment by wilku103** [comment]
thanks
