### ISSUE TITLE
no linux builds

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#23]
/releases only contain windows builds
I will create an ubuntu PPA if nobody has already done it (a quick PPA search on launchpad.net didn't find anything).

**Comment by Genoil** [comment]
hi,

that would be awesome! 

thanks

**Comment by nerdralph** [comment]
I only have AMD R9 cards, so I'm doing the PPA for OpenCL only.

**Comment by nerdralph** [comment]
Launchpad is fucked up and the guys in control have their heads up their aasses, so I wont be doing a ppa.  I'll still do a binary, either a .deb package for Ubuntu 14, and/or a statically-linked binary that would work on 14 thru 16.

**Comment by nerdralph** [comment]
I successfully built a .deb binary package, but I don't want it to conflict with the official ethminer (both are called /usr/bin/ethminer).  So I did a clean fork of 1.0.7 (https://github.com/nerdralph/cpp-ethereum), and added support for EXENAME (i.e. -DEXENAME=miner-genoil).  That worked fine and I pushed it to my fork.  I then copied it to the package build tree, but now it fails.
`dpkg-source: error: aborting due to unexpected upstream changes`

The debain packaging tools have their own rcs-like version control system, which makes little sense when git is being used for the source.  The statically-linked binary is looking like the easiest option now.  It will also allow for better optimization using lto and gcc-5.  If someone really wants a debian package, they can look at this guide I was following:
http://packaging.ubuntu.com/html/packaging-new-software.html

There may also be a way to integrate dpkg with git:
https://wiki.debian.org/PackagingWithGit/GitDpm

**Comment by nerdralph** [comment]
The executable name turns out to be the least of the conflicts.  Since this is a fork of the official ethminer, in order for the .deb to install, all the dependent libraries have to be the same versions (i.e. libcryptopp.so, ...)  In order to get my build to install, I had to completely uninstall cpp-ethereum-1.2.2.
It appears the only reasonable solution is a statically-linked binary.  That's what I'll try next.

```
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

ethminer version 0.9.41-genoil-1.0.7
Build: Linux/g++/int/None

```

**Comment by nerdralph** [comment]
Static builds are not working.
https://github.com/ethereum/webthree-umbrella/issues/337

I might try to get it fixed upstream first, if Bob and Chris are reasonable to work with.

**Comment by Genoil** [comment]
ok
