### ISSUE TITLE
recipe for target failed - Ubuntu 16.04

### ISSUE THREAD

**Issue by cameronhr** [Genoil/cpp-ethereum#232]
UPDATE: NEEDED TO RUN AS ROOT. PROBLEM SOLVED.

running make -j8 in build directory results in following:

[ 80%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
[ 82%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Params.cpp.o
[ 84%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 86%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Sealer.cpp.o
[ 89%] Linking CXX shared library libdevcore.so
[ 91%] Linking CXX shared library libethcore.so
[ 93%] Built target ethcore
[ 93%] Built target devcore
CMakeFiles/Makefile2:320: recipe for target 'libstratum/CMakeFiles/ethstratum.dir/all' failed
make[1]: *** [libstratum/CMakeFiles/ethstratum.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

in libstratum directory, there is no CMakeFiles subdirectory.

Fresh install of Ubuntu 16.04

**Comment by gsedej** [comment]
I am not a dev, but you should NEVER build as root.
The sudo should be used when installing after building `sudo make install`
