### ISSUE TITLE
getting 280x and quadro4000 to work

### ISSUE THREAD

**Issue by haniham** [Genoil/cpp-ethereum#233]
I just already had an 280x card in my computer.

I now installed an additional quadro 4000 into my compouter but ethminer isnt using it

C:\ethminer-0.9.41-genoil-1.1.7\ethminer-0.9.41-genoil-1.1.7>ethminer.exe --list-devices -G
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Tahiti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2214592512
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Quadro 4000
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

C:\ethminer-0.9.41-genoil-1.1.7\ethminer-0.9.41-genoil-1.1.7>

it seems to detect the quadro as open cl butr when i'm starting ethminer  with  
ethminer --farm-recheck 200 -G -S eth-eu1.nanopool.org:9999 -O (-:.MPC/mymail --cl-global-work 16834 --cl-local-work 256 -t 2 it's ignoring the 2nd card.

Additionally as i played around some time now my througoutput dropped from 12 MH/s to 8,5 
![grafik](https://user-images.githubusercontent.com/4102949/27390392-66c6704a-56a1-11e7-9ca4-2fc42d0f2028.png)

**Comment by omento** [comment]
what does `ethminer.exe -G --list-devices` return? You could (assuming you have both NVIDIA and AMD drivers installed) use CUDA with OpenCL using the `-X`.

**Comment by haniham** [comment]
Hey
ethminer.exe -G --list-devices returns:
ethminer.exe -G --list-devices
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Tahiti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952790016
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Quadro 4000
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

the quadro 4000 is only supporting opencl but not cuda
it was lying around so i wnated to try it out

**Comment by haniham** [comment]
the call with -X instead of -G
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable OpenCL device [Tahiti ] with 3221225472 bytes of GPU memory
  i  21:25:43|main  Connecting to stratum server eth-eu1.nanopool.org:9999
  i  21:25:43|stratum  Connected to stratum server eth-eu1.nanopool.org : 9999
  i  21:25:43|stratum  Starting farm
  i  21:25:43|stratum  Subscribed to stratum server
  i  21:25:43|stratum  Authorized worker 0x67a60f5d8ff3618882c1046c27be7ee6f4a3414b.MPC/markushahnenkamm@gmail.com
  i  21:25:43|stratum  Received new job #452c96c0
  i  21:25:43|cudaminer0  set work; seed: #129656ac, target: #00000000dbe6
  i  21:25:43|openclminer1  set work; seed: #129656ac, target: #00000000dbe6
  i  21:25:43|cudaminer0  Initialising miner...
  i  21:25:43|openclminer1  Initialising miner...
  m  21:25:44|main  Mining on PoWhash #452c96c0 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:25:44|main  Mining on PoWhash #452c96c0 : 0.00MH/s [A0+0:R0+0:F0]
Using platform: AMD Accelerated Parallel Processing
Using device: Tahiti(OpenCL 1.2 AMD-APP (2348.4))
  m  21:25:45|main  Mining on PoWhash #452c96c0 : 0.00MH/s [A0+0:R0+0:F0]
Using device: Quadro 4000 (Compute 2.0)
CUDA error in func 'ethash_cuda_miner::init' at line 243 : out of memory.

**Comment by omento** [comment]
Alright, so using CUDA is out of the question. Could you try running Ethminer with `opencl-devices 0 1` to try and force it to use the Quadro? It's either going to be `0 1` or `01`.

**Comment by haniham** [comment]
C:\ethminer-0.9.41-genoil-1.1.7\ethminer-0.9.41-genoil-1.1.7>ethminer --farm-recheck 500 -G -S eth-eu1.nanopool.org:9999 -O sdfgsadfsd --cl-global-work 16834 --cl-local-work 256 -t 2 --opencl-devices 0 1
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable OpenCL device [Tahiti ] with 3221225472 bytes of GPU memory
  i  21:46:20|main  Connecting to stratum server eth-eu1.nanopool.org:9999
  i  21:46:20|stratum  Connected to stratum server eth-eu1.nanopool.org : 9999
  i  21:46:20|stratum  Starting farm
  i  21:46:20|stratum  Subscribed to stratum server
  i  21:46:20|stratum  Authorized worker 0x67a60f5d8ff3618882c1046c27be7ee6f4a3414b.MPC/markushahnenkamm@gmail.com
  i  21:46:20|stratum  Received new job #aaad8635
  i  21:46:20|openclminer0  set work; seed: #129656ac, target: #00000000dbe6
  i  21:46:20|openclminer0  Initialising miner...
  m  21:46:20|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:21|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
Using platform: AMD Accelerated Parallel Processing
Using device: Tahiti(OpenCL 1.2 AMD-APP (2348.4))
  m  21:46:21|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
Printing program log

Creating cache buffer
Creating DAG buffer
Loading kernels
Writing cache buffer
Creating buffer for header.
Creating mining buffer 0
Creating mining buffer 1
Generating DAG data
  m  21:46:22|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:22|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:23|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:23|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:24|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:24|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:46:25|main  Mining on PoWhash #aaad8635 : 0.00MH/s [A0+0:R0+0:F0]

only uses the AMD GPU

only Nr 1 

C:\ethminer-0.9.41-genoil-1.1.7\ethminer-0.9.41-genoil-1.1.7>ethminer --farm-recheck 500 -G -S eth-eu1.nanopool.org:9999 -O 0x67a60f5d8ff3618882c1046c27be7ee6f4a3414b.MPC/markushahnenkamm@gmail.com --cl-global-work 16834 --cl-local-work 256 -t 2 --opencl-devices 1
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable OpenCL device [Tahiti ] with 3221225472 bytes of GPU memory
  i  21:49:43|main  Connecting to stratum server eth-eu1.nanopool.org:9999
  i  21:49:43|stratum  Connected to stratum server eth-eu1.nanopool.org : 9999
  i  21:49:43|stratum  Starting farm
  i  21:49:43|stratum  Subscribed to stratum server
  i  21:49:43|stratum  Authorized worker 0x67a60f5d8ff3618882c1046c27be7ee6f4a3414b.MPC/markushahnenkamm@gmail.com
  i  21:49:43|stratum  Received new job #3af2dd89
  i  21:49:43|openclminer0  set work; seed: #129656ac, target: #00000000dbe6
  i  21:49:43|openclminer0  Initialising miner...
  m  21:49:43|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:49:44|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:49:44|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
Using platform: AMD Accelerated Parallel Processing
Using device: Tahiti(OpenCL 1.2 AMD-APP (2348.4))
Printing program log

Creating cache buffer
Creating DAG buffer
Loading kernels
Writing cache buffer
Creating buffer for header.
Creating mining buffer 0
Creating mining buffer 1
Generating DAG data
  m  21:49:45|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:49:45|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:49:46|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:49:46|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
  m  21:49:47|main  Mining on PoWhash #3af2dd89 : 0.00MH/s [A0+0:R0+0:F0]
^C

**Comment by omento** [comment]
The only thing I can think of is that you haven't installed an [NVIDIA driver](http://www.nvidia.com/download/driverResults.aspx/120163/en-us) yet, otherwise I'm out of ideas.
