### ISSUE TITLE
Won't Generate DAG

### ISSUE THREAD

**Issue by cameronhr** [Genoil/cpp-ethereum#234]
Everything seems to work fine, until miner hangs generating DAG. Gets to 98% then stops and computer freezes. Can't cancel process, move mouse, etc.Terminal output below (note that I cancelled before it got to 98% to avoid crash, but would typically continue all the way to 98%).

Ubuntu 16.04.2
amdgpu-pro drivers
1x R9 290 4GB, stock
4GB system memory

$ ./ethminer --farm-recheck 200 -G -S us2.ethpool.org:3333 -FS us1.ethpool.org:3333 -O 0xf7A2655776318552A4d624ae1295b25F9756B790.CB02
Genoil's ethminer 0.9.41-genoil-1.1.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:Found suitable OpenCL device [Hawaii] with 3931291648 bytes of GPU memory
  ℹ  16:44:38|ethminer  Connecting to stratum server us2.ethpool.org:3333
  ℹ  16:44:38|stratum  Connected to stratum server us2.ethpool.org : 3333
  ℹ  16:44:38|stratum  Starting farm
  ℹ  16:44:38|stratum  Subscribed to stratum server
  ℹ  16:44:38|stratum  Authorized worker 0xf7A2655776318552A4d624ae1295b25F9756B790.CB02
  ℹ  16:44:38|stratum  Received new job #15a131b0
  ℹ  16:44:38|openclminer0  set work; seed: #129656ac, target:  #0000000112e0
  ℹ  16:44:38|openclminer0  Initialising miner...
  m  16:44:38|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:38|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:38|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:39|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:39|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:39|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:39|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:39|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:40|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:40|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:40|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:40|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:40|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:41|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:41|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:41|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:41|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:41|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:42|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:42|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:42|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:42|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:42|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:43|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:43|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:43|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:43|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:43|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:44|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  m  16:44:44|ethminer  Mining on PoWhash #15a131b0 : 0.00MH/s [A0+0:R0+0:F0]
  ℹ  16:44:44|stratum  Received new job #33b95095
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Hawaii(OpenCL 1.2 AMD-APP (2348.3))
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
[OPENCL]:Generating DAG data
OPENCL#0: 0%
OPENCL#0: 1%
OPENCL#0: 2%
OPENCL#0: 2%
OPENCL#0: 3%
OPENCL#0: 4%
OPENCL#0: 5%
OPENCL#0: 5%
OPENCL#0: 6%
OPENCL#0: 7%
OPENCL#0: 8%
OPENCL#0: 9%
OPENCL#0: 9%
OPENCL#0: 10%
OPENCL#0: 11%
OPENCL#0: 12%
OPENCL#0: 12%
OPENCL#0: 13%
OPENCL#0: 14%
OPENCL#0: 15%
OPENCL#0: 16%
OPENCL#0: 16%
OPENCL#0: 17%
OPENCL#0: 18%
OPENCL#0: 19%
OPENCL#0: 19%
OPENCL#0: 20%
OPENCL#0: 21%
OPENCL#0: 22%
OPENCL#0: 22%
OPENCL#0: 23%
OPENCL#0: 24%
OPENCL#0: 25%
OPENCL#0: 26%
OPENCL#0: 26%
OPENCL#0: 27%
OPENCL#0: 28%
OPENCL#0: 29%
OPENCL#0: 29%
OPENCL#0: 30%
OPENCL#0: 31%
OPENCL#0: 32%
OPENCL#0: 33%
OPENCL#0: 33%
OPENCL#0: 34%
OPENCL#0: 35%
OPENCL#0: 36%
OPENCL#0: 36%
OPENCL#0: 37%
OPENCL#0: 38%
OPENCL#0: 39%
OPENCL#0: 40%
OPENCL#0: 40%
OPENCL#0: 41%
OPENCL#0: 42%
OPENCL#0: 43%
OPENCL#0: 43%
OPENCL#0: 44%
OPENCL#0: 45%
OPENCL#0: 46%
OPENCL#0: 47%
OPENCL#0: 47%
OPENCL#0: 48%
OPENCL#0: 49%
OPENCL#0: 50%
OPENCL#0: 50%
OPENCL#0: 51%
OPENCL#0: 52%
OPENCL#0: 53%
OPENCL#0: 53%
OPENCL#0: 54%
OPENCL#0: 55%
OPENCL#0: 56%
OPENCL#0: 57%
OPENCL#0: 57%
OPENCL#0: 58%
OPENCL#0: 59%
OPENCL#0: 60%
OPENCL#0: 60%
OPENCL#0: 61%
OPENCL#0: 62%
OPENCL#0: 63%
OPENCL#0: 64%
OPENCL#0: 64%
OPENCL#0: 65%
OPENCL#0: 66%
OPENCL#0: 67%
OPENCL#0: 67%
OPENCL#0: 68%
OPENCL#0: 69%
OPENCL#0: 70%

**Comment by nikolehto** [comment]
#216

**Comment by cameronhr** [comment]
Thanks! Apologies for not finding the other issue.
