### ISSUE TITLE
_ALLOC_PERCENT options doing nothing?

### ISSUE THREAD

**Issue by danielocdh** [Genoil/cpp-ethereum#242]
I'm trying to limit the use on the GPU, is there a correct way to use the environment variables or they just don't work?
GPU_MAX_ALLOC_PERCENT
GPU_SINGLE_ALLOC_PERCENT

Right now I'm using with a single GPU on windows
setx GPU_MAX_ALLOC_PERCENT 40
setx GPU_SINGLE_ALLOC_PERCENT 40

Any ideas?

**Comment by danielocdh** [comment]
O.k. ?

**Comment by Genoil** [comment]
Adjust the global work size parameter to a lower value, i.e. 256
