### ISSUE TITLE
ethminer-0.9.41-genoil-1.1.9.zip, waits on package..

### ISSUE THREAD

**Issue by chabgood** [Genoil/cpp-ethereum#244]
Works on ethminer-0.9.41-genoil-1.1.7.zip but not on ethminer-0.9.41-genoil-1.1.9.zip
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O WALLET -U
Using grid size 8192, block size 128

  i  18:13:39|stratum  Connecting to stratum server eu1.ethermine.org:4444
  i  18:13:40|stratum  Connected!
  i  18:13:40|stratum  Starting farm
  i  18:13:40|stratum  Subscribed to stratum server
  i  18:13:40|stratum  Authorized worker 0x676dF2AF918D31F3ff5A2045F02F1E3E936Ce753.moo
  X  18:13:40|stratum  :-( Rejected in 1890 ms.
  m  18:13:40|main  Waiting for work package...
  m  18:13:40|main  Waiting for work package...
  m  18:13:40|main  Waiting for work package...
  m  18:13:40|main  Waiting for work package...
  m  18:13:41|main  Waiting for work package...
  m  18:13:41|main  Waiting for work package...
  X  18:13:41|stratum  :-( Rejected in 2937 ms.
  m  18:13:41|main  Waiting for work package...
  m  18:13:41|main  Waiting for work package...
  m  18:13:41|main  Waiting for work package...
  m  18:13:42|main  Waiting for work package...
  m  18:13:42|main  Waiting for work package...
  m  18:13:42|main  Waiting for work package...
  m  18:13:42|main  Waiting for work package...
  m  18:13:42|main  Waiting for work package...
  m  18:13:43|main  Waiting for work package...
  m  18:13:43|main  Waiting for work package...
  m  18:13:43|main  Waiting for work package...
  m  18:13:43|main  Waiting for work package...
  m  18:13:43|main  Waiting for work package...
  m  18:13:44|main  Waiting for work package...
  m  18:13:44|main  Waiting for work package...
  m  18:13:44|main  Waiting for work package...
  m  18:13:44|main  Waiting for work package...
  m  18:13:44|main  Waiting for work package...
  m  18:13:45|main  Waiting for work package...
  m  18:13:45|main  Waiting for work package...
  m  18:13:45|main  Waiting for work package...
  m  18:13:45|main  Waiting for work package...
  m  18:13:45|main  Waiting for work package...
  m  18:13:46|main  Waiting for work package...
  m  18:13:46|main  Waiting for work package...
  m  18:13:46|main  Waiting for work package...
  m  18:13:46|main  Waiting for work package...
  m  18:13:47|main  Waiting for work package...
  m  18:13:47|main  Waiting for work package...
  m  18:13:47|main  Waiting for work package...
  m  18:13:47|main  Waiting for work package...
  X  18:13:47|stratum  :-( Rejected in 9254 ms.
  m  18:13:47|main  Waiting for work package...
  m  18:13:48|main  Waiting for work package...
  m  18:13:48|main  Waiting for work package...
  m  18:13:48|main  Waiting for work package...
  m  18:13:48|main  Waiting for work package...
  m  18:13:48|main  Waiting for work package...
  m  18:13:49|main  Waiting for work package...
  m  18:13:49|main  Waiting for work package...
  m  18:13:49|main  Waiting for work package...
  m  18:13:49|main  Waiting for work package...
  m  18:13:49|main  Waiting for work package...
  m  18:13:50|main  Waiting for work package...
  m  18:13:50|main  Waiting for work package...
  m  18:13:50|main  Waiting for work package...
  m  18:13:50|main  Waiting for work package...
  m  18:13:50|main  Waiting for work package...
  m  18:13:51|main  Waiting for work package...
  m  18:13:51|main  Waiting for work package...
  m  18:13:51|main  Waiting for work package...
  m  18:13:51|main  Waiting for work package...
  m  18:13:51|main  Waiting for work package...
  m  18:13:52|main  Waiting for work package...
  m  18:13:52|main  Waiting for work package...
  m  18:13:52|main  Waiting for work package...
  m  18:13:52|main  Waiting for work package...
  m  18:13:52|main  Waiting for work package...
  m  18:13:53|main  Waiting for work package...
  m  18:13:53|main  Waiting for work package...
  m  18:13:53|main  Waiting for work package...
  m  18:13:53|main  Waiting for work package...
  m  18:13:53|main  Waiting for work package...
  m  18:13:54|main  Waiting for work package...
  m  18:13:54|main  Waiting for work package...
  m  18:13:54|main  Waiting for work package...
  m  18:13:54|main  Waiting for work package...
  m  18:13:54|main  Waiting for work package...
  m  18:13:55|main  Waiting for work package...
  m  18:13:55|main  Waiting for work pac

**Comment by LinuxDonald** [comment]
Is ethminer-0.9.41-genoil-1.1.9.zip an offical version because i dont find it.

**Comment by chabgood** [comment]
It is here, https://github.com/Genoil/cpp-ethereum/tree/110/releases

**Comment by LinuxDonald** [comment]
It fails for me too :(

**Comment by Genoil** [comment]
1.1.9 was done by @nerdralph, not tested very well. I'd stick with 1.1.7

**Comment by LinuxDonald** [comment]
Is ethminer-genoil still in developement? Because i found an fork of it: https://github.com/ethereum-mining/ethminer and this is very active.

**Comment by Genoil** [comment]
No, not really. The fork by @chfast, who has been contributing to the original ethminer possibly more than I ever did, looks very promising. I might just refork from there at some point :)

**Comment by chfast** [comment]
I'd preferably join forces on this.

**Comment by Genoil** [comment]
That implies I have to actually DO things ;). I was actually considering replacing my readme with a link to your fork, close down the issues section and see from there.

**Comment by chfast** [comment]
This is still fine for me. I just try to avoid competing features here and there.
