### ISSUE TITLE
getstuff.bat fails on Win 10

### ISSUE THREAD

**Issue by Robzilla** [Genoil/cpp-ethereum#246]
Hi all, have a fresh copy of Win 10, cloned the github repo and tried to run getstuff.bat but received the error shown below. Tried to get the file manually using a browser but it wasn't there. Not behind a corporate firewall or proxy so none of those blockers are present.

DISPLAY: '{A6D36755-2556-4741-850D-9946230AE296}' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR
PRIORITY: NORMAL FILES: 0 / 1 BYTES: 0 / UNKNOWN
ERROR FILE:    https://build.ethdev.com/builds/windows-precompiled/boost-1.55.0-x64.tar.gz -> C:\Users\Robert\Documents\GitHub\cpp-ethereum\extdep
ERROR CODE:    0x80072ee2
ERROR CONTEXT: 0x00000005

**Comment by starbuck93** [comment]
I'm also experiencing this. Read #183
