### ISSUE TITLE
Duplicate repositories are confusing users

### ISSUE THREAD

**Issue by JHGitty** [Genoil/cpp-ethereum#268]
See https://github.com/ethereum-mining/ethminer/issues/154

@Genoil Can you explain us what is happening here? Which repo is the newest and best for everybody? Which is obsolete?

**Comment by JHGitty** [comment]
In case that this repo will be obsolete because of the other repo: Can we add a big text on the README to inform the users about that?

**Comment by cryocaustik** [comment]
Spent several hours trying to get this to work, only to realize that the updated version was in another repo. 

Would be very helpful to have a note in the README.

**Comment by Genoil** [comment]
yeah sorry about that. i just dropped the refork and switched back to making the 117 the default branch. for historical purposes you know
