### ISSUE TITLE
Installing the binary

### ISSUE THREAD

**Issue by sebastianheyn** [Genoil/cpp-ethereum#273]
Sorry for asking such a retarded question. 

Howto install the comiled binary? can I simply copy the binary or does it need any libraries?

**Comment by keraj37** [comment]
Basically what you get as a result of building is all you need. But sometimes you will need some dynamic libraries to be copied into the same folder of executable file, so it will be portable.
So there is no "installing", but simple copy wherever you like and run this executable file as CLI.

**Comment by sebastianheyn** [comment]
ok thanks! thats what I did
