### ISSUE TITLE
The add more memory option has 0 effect 

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [Genoil/cpp-ethereum#274]
So I've been using `./ethminer --farm-recheck 200 --cuda-block-size 512 --cuda-schedule spin -U -S us1-etc.ethermine.org:4444 --cl-extragpu-mem 1024 --cuda-extragpu-mem 1024 -O 0x11d8f585ac87c8f0dfa2fa35962cab4210db05a4.PC1 #-FO 127.0.0.1:2545
` to mine but the extra gpu flag does nothing, it still only uses 2 gb of vram! it would be even better if this could also use a combination of system ram too, but I see how that might not work...

**Comment by JHGitty** [comment]
Hey! :-)

The ethminer got forked and is now in a new repository here: https://github.com/ethereum-mining/ethminer/

Please try out the newest release there. The "genoil" ethminer is outdated right now.

**Comment by gidoBOSSftw5731** [comment]
Oh, I always heard this being a good miner, will swap!
