### ISSUE TITLE
OSX build issue: undeclared identifier CL_DEVICE_COMPUTE_CAPABILITY_MAJOR_NV

### ISSUE THREAD

**Issue by nmushegian** [Genoil/cpp-ethereum#28]
I tried to use the Ubuntu guide and the official webthree OSX guides for guidance.

```
[ 58%] Building CXX object libethash-cl/CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.o
/Users/nikolai/genoilminer/libethash-cl/ethash_cl_miner.cpp:374:30: error: use of undeclared identifier
      'CL_DEVICE_COMPUTE_CAPABILITY_MAJOR_NV'
                        clGetDeviceInfo(device(), CL_DEVICE_COMPUTE_CAPABILITY_MAJOR_NV, sizeof(cl_uint), &compu...
                                                  ^
/Users/nikolai/genoilminer/libethash-cl/ethash_cl_miner.cpp:375:30: error: use of undeclared identifier
      'CL_DEVICE_COMPUTE_CAPABILITY_MINOR_NV'
                        clGetDeviceInfo(device(), CL_DEVICE_COMPUTE_CAPABILITY_MINOR_NV, sizeof(cl_uint), &compu...
```

**Comment by loxal** [comment]
same issue over here

**Comment by Genoil** [comment]
fixed with https://github.com/Genoil/cpp-ethereum/commit/ca4e14ebd7425285a52b33e81be484747669309d

**Comment by loxal** [comment]
@Genoil Thanks, the mentioned compilation error is gone but I get
> 
> [ 31%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FileSystem.cpp.o
> In file included from /Users/alex/Downloads/cpp-ethereum/libethash-cl/ethash_cl_miner.cpp:40:
> /Users/alex/Downloads/cpp-ethereum/libethash-cl/ethash_cl_miner.h:9:10: fatal error: 'CL/cl.hpp' file not found
> #include "CL/cl.hpp"
>          ^
> 1 error generated.
> make[2]: *** [libethash-cl/CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.o] Error 1
> make[1]: *** [libethash-cl/CMakeFiles/ethash-cl.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 33%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FixedHash.cpp.o

…building the `108` branch.

**Comment by Genoil** [comment]
@loxal my bet is on `#include "OpenCL/cl.hpp"` but I'm not 100% sure. Can you verify? Otherwise do a system wide search for cl.hpp.

**Comment by loxal** [comment]
@Genoil actually far simpler, I had to omit the folder as the file is located in `cpp-ethereum/libethash-cl/cl.hpp`. Still what I get now is 

> [ 60%] Linking CXX shared library libethstratum.dylib
> Undefined symbols for architecture x86_64:
>   "dev::NoteChannel::name()", referenced from:
>       EthStratumClient::connect() in EthStratumClient.cpp.o
>       EthStratumClient::reconnect() in EthStratumClient.cpp.o
>       EthStratumClient::disconnect() in EthStratumClient.cpp.o
>       EthStratumClient::connect_handler(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>) in EthStratumClient.cpp.o
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>       EthStratumClient::work_timeout_handler(boost::system::error_code const&) in EthStratumClient.cpp.o
>       EthStratumClient::submit(dev::eth::EthashProofOfWork::Solution) in EthStratumClient.cpp.o
>       ...
>   "dev::TimerHelper::~TimerHelper()", referenced from:
>       dev::eth::GenericMiner<dev::eth::EthashProofOfWork>::setWork(dev::eth::EthashProofOfWork::WorkPackage const&) in EthStratumClient.cpp.o
>   "dev::WarnChannel::name()", referenced from:
>       EthStratumClient::connect_handler(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>) in EthStratumClient.cpp.o
>       EthStratumClient::handleResponse(boost::system::error_code const&) in EthStratumClient.cpp.o
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>       EthStratumClient::submit(dev::eth::EthashProofOfWork::Solution) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::WarnChannel, true>::~LogOutputStream() in EthStratumClient.cpp.o
>   "dev::setThreadName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
>       EthStratumClient::connect_handler(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>) in EthStratumClient.cpp.o
>       EthStratumClient::handleResponse(boost::system::error_code const&) in EthStratumClient.cpp.o
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>   "dev::g_logVerbosity", referenced from:
>       dev::LogOutputStream<dev::NoteChannel, true>& dev::LogOutputStream<dev::NoteChannel, true>::operator<<<char [30]>(char const (&) [30]) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::NoteChannel, true>::operator<<(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::NoteChannel, true>& dev::LogOutputStream<dev::NoteChannel, true>::operator<<<char [29]>(char const (&) [29]) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::NoteChannel, true>& dev::LogOutputStream<dev::NoteChannel, true>::operator<<<char [14]>(char const (&) [14]) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::NoteChannel, true>& dev::LogOutputStream<dev::NoteChannel, true>::operator<<<char [2]>(char const (&) [2]) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::WarnChannel, true>& dev::LogOutputStream<dev::WarnChannel, true>::operator<<<char [37]>(char const (&) [37]) in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::WarnChannel, true>::operator<<(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in EthStratumClient.cpp.o
>       ...
>   "dev::LogOutputStreamBase::LogOutputStreamBase(char const*, std::type_info const*, unsigned int, bool)", referenced from:
>       EthStratumClient::connect() in EthStratumClient.cpp.o
>       EthStratumClient::reconnect() in EthStratumClient.cpp.o
>       EthStratumClient::disconnect() in EthStratumClient.cpp.o
>       EthStratumClient::connect_handler(boost::system::error_code const&, boost::asio::ip::basic_resolver_iterator<boost::asio::ip::tcp>) in EthStratumClient.cpp.o
>       EthStratumClient::handleResponse(boost::system::error_code const&) in EthStratumClient.cpp.o
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>       ...
>   "dev::eth::EthashAux::computeFull(dev::FixedHash<32u> const&, bool)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "dev::eth::EthashAux::eval(dev::FixedHash<32u> const&, dev::FixedHash<32u> const&, dev::FixedHash<8u> const&)", referenced from:
>       EthStratumClient::submit(dev::eth::EthashProofOfWork::Solution) in EthStratumClient.cpp.o
>   "dev::eth::EthashAux::full(dev::FixedHash<32u> const&, bool, std::__1::function<int (unsigned int)> const&)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "dev::sha3(dev::vector_ref<unsigned char const>, dev::vector_ref<unsigned char>)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "dev::fromHex(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, dev::WhenError)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "dev::g_logPost", referenced from:
>       dev::LogOutputStream<dev::NoteChannel, true>::~LogOutputStream() in EthStratumClient.cpp.o
>       dev::LogOutputStream<dev::WarnChannel, true>::~LogOutputStream() in EthStratumClient.cpp.o
>   "Json::Value::null", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::Value(Json::ValueType)", referenced from:
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::Value(char const*)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::Value(bool)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::~Value()", referenced from:
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::operator=(Json::Value)", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Reader::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Json::Value&, bool)", referenced from:
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>   "Json::Reader::Reader()", referenced from:
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
>   "Json::Value::get(char const*, Json::Value const&) const", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::get(unsigned int, Json::Value const&) const", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::asInt() const", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::asBool() const", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::isArray() const", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Value::asString() const", referenced from:
>       EthStratumClient::processReponse(Json::Value&) in EthStratumClient.cpp.o
>   "Json::Reader::getFormattedErrorMessages() const", referenced from:
>       EthStratumClient::readResponse(boost::system::error_code const&, unsigned long) in EthStratumClient.cpp.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [libstratum/libethstratum.dylib] Error 1
> make[1]: *** [libstratum/CMakeFiles/ethstratum.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

**Comment by Genoil** [comment]
yeah i just noticed that cl.hpp still being there. it's an old opencl 1.1 header but if it helps, fine. these new errors are a bit over my head. i have never had anybody with OSX build issues like these. they mostly choke on building he CUDA components.

**Comment by loxal** [comment]
I have not found cl.hpp anywhere else. Maybe *because* it’s so old, it causes issues as I have the newest CUDA driver installed (v7.5.26).
