### ISSUE TITLE
ethminer crashes when disconnected

### ISSUE THREAD

**Issue by miningpoolhub** [Genoil/cpp-ethereum#32]
ethminer crashes in this scenario.

1. Server disconnects ethminer.
2. ethminer try to reconnect quickly
3. server disconnects ethminer again.
I didn't build ethminer.exe, just ran latest release 1.0.7 genoil-ethminer and found this bug.

Maybe I would build ethminer.exe by myself and debug but you would already catch the problem by this screenshot.

![image](https://cloud.githubusercontent.com/assets/6733455/14957042/143a3aca-10be-11e6-8d8f-e97492b28671.png)

Read response failed: "Wrong file handle" in english.

**Comment by Genoil** [comment]
Is that even 1.0.7? I thought I disabled farm stop on connection failure. 

I would need a way to control server-side disconnects. Can you set up a server that I can remote into to start/stop?

**Comment by miningpoolhub** [comment]
This is 1.0.7
You can test from miningpoolhub.com

1. Sign up
2. Click "Hub Workers" page. https://miningpoolhub.com/?page=account&action=hubworkers
3. Change "Account's Default Job" to Ethash or Ethereum.
4. Configure miner settings and run
    ethminer --farm-retries 0 -G -S hub.miningpoolhub.com:12020 -O username.workername:x
    ethminer --farm-retries 0 -G -S hub.miningpoolhub.com:12020 -O username.workername:x -FS exit
5. Change Account's Default Job to "No Work" or other coin to disconnect.

**Comment by Genoil** [comment]
I tested this using your guide. 1st of all it doesn't crash, it exists normally. This is intended behavior, because as soon as you change the Job to "No Work",  the client disconnects, then attempts a reconnect. The reconnection fails because the worker cannot be authorized, causing ethminer to exit. Would you prefer the miner to stay connected and retrying to authorize forever?

**Comment by miningpoolhub** [comment]
Well closing normally is what I intended.
I created issue because ethminer crashed, and stopped with error dialog. I clicked "Debug" button from that. (You would know what I'm talking about if you have seen crash dialog from Windows. There was Debug button because I installed Visual Studio.)
The screenshot showing Visual Studio is what I get after clicking Debug button. I didn't have debug symbol PDB file at that time, so stack traces are corrupted, but that Disassembly is the crash point I got. Maybe map file generation would be helpful to find the crash point, if you have all build system not changed. (This was 1.0.7 release binary from github you uploaded)

I tested it today again with same binary, same batch settings, but couldn't reproduce it.
I saw crash three times at that time about 50% probability, but I'm curious why I don't see now.
Maybe because I rebooted, and ATI GPU related thing changed or Windows update affected.
Or maybe ethminer was managing DAG file at that time, and immediate closing have affected that.

I also tested DAG remake thing, but couldn't reproduce.
Do you have any idea something scheduled work or thread from ethminer that is not prepared for immediate close?

If there's no more things you can think of, I think this issue can be closed as I can't reproduce now.
Very weird, but I don't understand this situation.

**Comment by Genoil** [comment]
okidoki
