### ISSUE TITLE
Have issues using 2nd device

### ISSUE THREAD

**Issue by DaveBarrron** [Genoil/cpp-ethereum#33]
C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G --list-devices
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
**[0] GeForce GTX 970**
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
**[1] Tahiti**
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952232028
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

--------------------
**[1] is actually R9 280X

I can't get it to recognize "[1] is actually R9 280X"**

C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G **--opencl-device 1** -F h
ttp://eth-us.dwarfpool.com:80/0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2/rig1/ma
geon@aol.com

C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G **--opencl-devices 1** -F
http://eth-us.dwarfpool.com:80/0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2/rig1/m
ageon@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable OpenCL device [GeForce GTX 970] with 4294967296 bytes of GPU memo
ry
miner  12:00:55|main  Getting work package...
miner  12:00:56|main  Grabbing DAG for #17a7217fΓÇª
miner  12:00:57|main  Got work package:
miner  12:00:57|main    Header-hash: d84e9cca830295ec80e5fc183dac6208dfa18aba81a
130f3d7eedbfda1d8165f
miner  12:00:57|main    Seedhash: 17a7217f2673ce6267021cc82e7b328a755f010d6741bd
e6c25d3c2b0373e989
miner  12:00:57|main    Target: 0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178
046aeb27ce1ca574
  i  12:00:57|<unknown>  Loading full DAG of seedhash: #95d53b63ΓÇª
  i  12:00:57|gpuminer0  workLoop 0 #00000000ΓÇª #17a7217fΓÇª
  i  12:00:57|gpuminer0  Initialising miner...
miner  12:00:57|main  Mining on PoWhash #d84e9ccaΓÇª : 0 H/s = 0 hashes / 0.53 s

Using platform: NVIDIA CUDA
Using device: GeForce GTX 970(OpenCL 1.2 CUDA)
Printing program log

Creating one big buffer for the DAG
Loading single big chunk kernels
Mapping one big chunk.
miner  12:00:58|main  Mining on PoWhash #d84e9ccaΓÇª : 0 H/s = 0 hashes / 1.12 s

C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G **--opencl-devices 0** -F
http://eth-us.dwarfpool.com:80/0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2/rig1/m
ageon@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

Found suitable OpenCL device [GeForce GTX 970] with 4294967296 bytes of GPU memo
ry
miner  12:02:44|main  Getting work package...
miner  12:02:44|main  Grabbing DAG for #17a7217fΓÇª
  i  12:02:45|<unknown>  Loading full DAG of seedhash: #95d53b63ΓÇª
miner  12:02:45|main  Got work package:
miner  12:02:45|main    Header-hash: dc638107d8ece5367dda76f3f62f515bdf4b14033c3
cf063736b91807bcce821
miner  12:02:45|main    Seedhash: 17a7217f2673ce6267021cc82e7b328a755f010d6741bd
e6c25d3c2b0373e989
miner  12:02:45|main    Target: 0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178
046aeb27ce1ca574
  i  12:02:45|gpuminer0  workLoop 0 #00000000ΓÇª #17a7217fΓÇª
  i  12:02:45|gpuminer0  Initialising miner...
miner  12:02:46|main  Mining on PoWhash #dc638107ΓÇª : 0 H/s = 0 hashes / 0.505
s
Using platform: NVIDIA CUDA
Using device: GeForce GTX 970(OpenCL 1.2 CUDA)
Printing program log

Creating one big buffer for the DAG
Loading single big chunk kernels
Mapping one big chunk.
miner  12:02:47|main  Mining on PoWhash #dc638107ΓÇª : 0 H/s = 0 hashes / 1.07 s

**Comment by Genoil** [comment]
If you want to mine using the 280X (Tahiti) you have to specify a different --opencl-platform, i.e. 1. You can't use an AMD GPU on Nvidia OpenCL.

**Comment by DaveBarrron** [comment]
Can you please let me know the correct command for:
C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G    --list-devices
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d




Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 970
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] Tahiti
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2952232028
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256


I tried: -U -G with  --opencl-platform 1 

C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G --opencl-platform 1 --
opencl-device 1 -U --cuda-devices 0 --farm-recheck 500 -F http://eth-eu.dwarfpoo
l.com:80/0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2/rig2/mageon@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Using grid size 8192, block size 128


Found suitable CUDA device [GeForce GTX 970] with 4294967296 bytes of GPU memory


miner  05:28:39|main  Getting work package.


Without -U (only sees Tahiti)

C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G --opencl-platform 1 -
opencl-device 1  --cuda-devices 0 --farm-recheck 500 -F http://eth-eu.dwarfpool
com:80/0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2/rig2/mageon@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Found suitable OpenCL device [Tahiti] with 3221225472 bytes of GPU memory
miner  05:30:50|main  Getting work package...
miner  05:30:51|main  Grabbing DAG for #17a7217fΓÇª



I tried  --opencl-platform 1 -- opencl-device 1  --opencl-platform 0 --opencl-device 0 (only see 970)



C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G --opencl-platform 1 --
opencl-device 1  --opencl-platform 0 --opencl-device 0 --farm-recheck 500 -F htt
p://eth-eu.dwarfpool.com:80/0xc835e52bd00f91ffa0ca39cf745e03986fdbb8e2/rig2/mage
on@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Found suitable OpenCL device [GeForce GTX 970] with 4294967296 bytes of GPU memo
ry




C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G --opencl-platform 1 -
opencl-device 1  --farm-recheck 500 -F http://eth-eu.dwarfpool.com:80/0xc835e52
d00f91ffa0ca39cf745e03986fdbb8e2/rig2/mageon@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Found suitable OpenCL device [Tahiti] with 3221225472 bytes of GPU memory
miner  05:34:53|main  Getting work package...



(continues to work)


(start a 2nd cmd session)
C:\mine\ethminer-0.9.41-genoil-1.0.7\CUDA 7.5>ethminer -G --opencl-platform 0 --
opencl-device 0  --farm-recheck 500 -F http://eth-eu.dwarfpool.com:80/0xc835e52b
d00f91ffa0ca39cf745e03986fdbb8e2/rig2/mageon@aol.com
Genoil's ethminer 0.9.41-genoil-1.0.7
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_


Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d


Found suitable OpenCL device [GeForce GTX 970] with 4294967296 bytes of GPU memo
ry
miner  05:35:12|main  Getting work package...
miner  05:35:13|main  Grabbing DAG for #17a7217fΓÇª
(stops working)


I am really trying to figure this out.


-----Original Message-----

**Comment by Genoil** [comment]
That's the correct output of -G --list-devices? I have exactly the same hardware in my machine and the output from the command is also just like that.

**Comment by Genoil** [comment]
Please contact me on forum.ethereum.org for operational support. I'd like to keep this section to functional/technical issues.
