### ISSUE TITLE
core dump in timeout failover code

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#38]
ℹ  08:00:13|stratum  No new work received in 90 seconds.
  ✘  08:00:13|stratum  Read response failed: Operation canceled
  ℹ  08:00:13|stratum  Reconnecting in 3 seconds...
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  close: Bad file descriptor
Aborted (core dumped)

This is a build on Ubuntu 14.04 of 108 branch as of 2016/05/11 22:00 UTC.

**Comment by Genoil** [comment]
Of course Windows never complained about my sloppy coding. I guess I need better exception handling on the stratum handlers, because they still return after the reconnect has been initiated.

**Comment by Genoil** [comment]
I'm trying to reproduce this. I do get Bad file descriptors, but it just ploughs on. Can you consistently reproduce this? You can set short timeout using --work-timeout param.

**Comment by nerdralph** [comment]
Was able to reproduce it after several minutes of mining with --work-timeout 20.  Looking at the logs, wasn't after the first timeout, it was after the 7th.  The logs from the first time it occurred (when I reported the issue), the crash happened after the 3rd timeout.

**Comment by Genoil** [comment]
Cool. Since i can't reproduce, would you care to debug the issue and fix it?

**Comment by nerdralph** [comment]
Will give it a shot. Haven't used boost before so could be a bit of learning curve.  There's also the danger that I might not like some of your code and end up doing more than just fix the bug. :-)

**Comment by Genoil** [comment]
you're welcome :)
