### ISSUE TITLE
Different Brands 270x Cards Can't Mine

### ISSUE THREAD

**Issue by harrisboyuno** [Genoil/cpp-ethereum#40]
Hello, I have 2 different brands of 270x cards. Two XFX and one Powercolor. I know the DAG file hasn't grown past 2GB because the XFX cards are working, but my Powercolor card gives me the error that I cannot mine due to insufficient memory.

**Comment by lightningpo** [comment]
I experience similar issue with my ASUS R9 270X, but using the 1.0.8 version it works, but 1.1.5 doesn't

**Comment by Genoil** [comment]
see readme for environment vars to set
