### ISSUE TITLE
Ubuntu 16.04 LTS - able to see my GPU now - can't increase mem or heap size

### ISSUE THREAD

**Issue by evrotrash** [Genoil/cpp-ethereum#41]
Hi All,
After upgrading to 16.04 I thought I couldn't mine anymore. Luck has it that the AMDGPU driver supports opencl now and is available.
when I run ethminer --list-devices I get this:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] AMD PITCAIRN (DRM 2.43.0, LLVM 3.8.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 1073741824
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 268435456
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

The CL Device Global Mem size is set to 50%. The old commands to increase heap size and single alloc that worked with the old drivers doesn't work anymore. I ran:
export GPU_FORCE_64BIT_PTR=0
export GPU_MAX_HEAP_SIZE=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_ALLOC_PERCENT=100
export GPU_SINGLE_ALLOC_PERCENT=100

None of them were able to increase the memory the size remains the same. Does anyone know how to free my memory using the new amdgpu kernel driver in Ubuntu 16.04? My R9 290 is sitting idle, i'll tip whoever gives me an answer :)

Rgds

**Comment by jstefanop** [comment]
its a bug in the AMDGPU driver...cant do anything until they fix it. Best bet is to downgrade to 14.04 and use fglrx.
