### ISSUE TITLE
build fails on linux mint 17.3

### ISSUE THREAD

**Issue by unxed** [Genoil/cpp-ethereum#42]
Scanning dependencies of target ethminer
[100%] Building CXX object ethminer/CMakeFiles/ethminer.dir/main.cpp.o
In file included from /home/unxed/eth/cpp-ethereum/ethminer/main.cpp:39:0:
/home/unxed/eth/cpp-ethereum/ethminer/MinerAux.h: In member function ‘void MinerCLI::doStratum()’:
/home/unxed/eth/cpp-ethereum/ethminer/MinerAux.h:1061:13: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
     else if (client.waitState() == MINER_WAIT_STATE_WORK)
             ^
Linking CXX executable ethminer
../libethash-cl/libethash-cl.so: error: undefined reference to 'clRetainDevice'
../libethash-cl/libethash-cl.so: error: undefined reference to 'clReleaseDevice'
collect2: error: ld returned 1 exit status
make[2]: *** [ethminer/ethminer] Error 1
make[1]: *** [ethminer/CMakeFiles/ethminer.dir/all] Error 2
make: *** [all] Error 2

**Comment by unxed** [comment]
GPU nvidia 8600GT, driver version 340.96

**Comment by Genoil** [comment]
ethash-cl requires OpenCL 1.2 support. I don't think that exists for the 8600GT. Same goed for ethash-cuda, requires Compute 3.0 (2.0 support also available soon). But 8600GT is 1.1.

**Comment by unxed** [comment]
thanks!

**Comment by unxed** [comment]
same issue with intel sandy bridge apu.
opencl libs installed by this tutorial:
https://software.intel.com/en-us/forums/opencl/topic/390630

``

In file included from /home/squaw/eth/cpp-ethereum/ethminer/main.cpp:39:0:
/home/squaw/eth/cpp-ethereum/ethminer/MinerAux.h: In member function ‘void MinerCLI::doStratum()’:
/home/squaw/eth/cpp-ethereum/ethminer/MinerAux.h:1061:13: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
     else if (client.waitState() == MINER_WAIT_STATE_WORK)
             ^
Linking CXX executable ethminer
[100%] Built target ethminer

``
