### ISSUE TITLE
miner does not see intel opencl device

### ISSUE THREAD

**Issue by unxed** [Genoil/cpp-ethereum#43]
"ethminer --list-devices" does not show my opencl-enabled intel sandy bridge apu. opencl libs installed by this tutorial:
https://software.intel.com/en-us/forums/opencl/topic/390630

platform: linux mint 17.3 x64 

clinfo tool says:

Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 1.2 LINUX
  Platform Name:				 Intel(R) OpenCL
  Platform Vendor:				 Intel(R) Corporation
  Platform Extensions:				 cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64 

  Platform Name:				 Intel(R) OpenCL
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_CPU
  Device ID:					 32902
  Max compute units:				 4
  Max work items dimensions:			 3
    Max work items[0]:				 8192
    Max work items[1]:				 8192
    Max work items[2]:				 8192
  Max work group size:				 8192
  Preferred vector width char:			 1
  Preferred vector width short:			 1
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 8
  Native vector width double:			 4
  Max clock frequency:				 2500Mhz
  Address bits:					 64
  Max memory allocation:			 2514811904
  Image support:				 Yes
  Max number of images read arguments:		 480
  Max number of images write arguments:		 480
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 480
  Max size of kernel argument:			 3840
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 No
    Round to +ve and infinity:			 No
    IEEE754-2008 fused multiply-add:		 No
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 262144
  Global memory size:				 10059247616
  Constant buffer size:				 131072
  Max number of constant args:			 480
  Local memory type:				 Global
  Local memory size:				 32768
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x1bc0780
  Name:						        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  Vendor:					 Intel(R) Corporation
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 1.2.0.43
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 (Build 43)
  Extensions:					 cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64

**Comment by Genoil** [comment]
There's a cmd line flag --allow-opencl-cpu 1. This should enable it, altough I've never tried. You will likely run into memory allocation issues. That may be solved using a kernel where the DAG emmeory is split across multiple chunks. Let me know if you need code for that.

**Comment by unxed** [comment]
Just as you said, I've got a segfault trying to mine with --allow-opencl-cpu turned on.

> Let me know if you need code for that.

Yes, please. I'm certainly want to give it a try.

**Comment by Genoil** [comment]
As I mentioned in the other thread, the code seems to have already passed the main DAG memory allocation part. So in theory you shouldn't have to use chunks. Intel CPUs don't get this far. I'd just run a debugger to see where the segfault comes from. I can hand you the chunks code, but if it isn't a problem, better not use chunks (worse performance).

**Comment by Genoil** [comment]
Let's continue here https://github.com/Genoil/cpp-ethereum/issues/44
