### ISSUE TITLE
miner segfaults with --allow-opencl-cpu option turned on

### ISSUE THREAD

**Issue by unxed** [Genoil/cpp-ethereum#44]
I have 16Gb of main memory installed, if it matters.

[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Oland(OpenCL 1.2 AMD-APP (1800.11))
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: AMD FX(tm)-8120 Eight-Core Processor(OpenCL 1.2 AMD-APP (1800.11))
  m  13:53:52|ethminer  Got work package: #52eb7fa0
  ℹ  13:53:52|ethminer  Full DAG loaded
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
./run.sh: line 13:  4794 Segmentation fault                   ./ethminer --farm-recheck 2000 --allow-opencl-cpu -G -F http://127.0.0.1:8080/rig1

**Comment by Genoil** [comment]
Well it got further than I expected :). If you want to try fixing it, please be my guest! I personally have no intentions of doing so.

**Comment by unxed** [comment]
Thanks for support! Unfortunately, I'm not so familar with deugging process, but I can try if you give me some basic instructions. And about chunks code: if there are no other choices to get my cpu mining, performace degree does not matters :)

**Comment by unxed** [comment]
Right now I can do some experiments with AMD CPU mentioned in #43, but in an hour or two I will try on Intel also.

**Comment by Genoil** [comment]
For some reason my CPU mining code is broken too. And i will also not fix this, because in the next release I will generate the DAG file on the GPU only. I would advise to use the stock Ethereum miner for CPU mining support. https://github.com/ethereum/webthree-umbrella

**Comment by unxed** [comment]
ok, I will try it, thanks. and that is the reason of DAG generation on the fly? is it faster then downloading entire data?
