### ISSUE TITLE
can't build on Windows

### ISSUE THREAD

**Issue by KlausT** [Genoil/cpp-ethereum#45]
If I try to build it with VS2013 I get this error:

> LINK : fatal error LNK1181: cannot open input file 'pthread.lib'

Is pthread missing in getstuff.bat?
Or is it actually not needed?

**Comment by Genoil** [comment]
No you can remove it. It's a bug in the cmake script that I still need to fix.

**Comment by KlausT** [comment]
Why does Linux needs pthread, but Windows don't? That's wierd.
Anyway, how do I test for "not Windows" in CMakeLists.txt ?

**Comment by Genoil** [comment]
To be honest I'm not entirely sure, but when compiling on Ubuntu this line at least doesn't cause trouble :)
