### ISSUE TITLE
CUDA won't build on Debian or Ubuntu

### ISSUE THREAD

**Issue by int03h** [Genoil/cpp-ethereum#49]
I have actually managed to get this to build on both Ubuntu and Debian using some of the instructions in the README included with the bundle. I won't repeat them to keep this brief. 

I have managed to get the ETHCL version since 1.0.8 to build and work. 

I simply can't get the CUDA version to build. Every time I try it breaks here : 

[ 58%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:207 (message):
  Error generating
  /src/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: **\* [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: **\* [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
root@eth:/src/cpp-ethereum/build#

I have cuda-toolkit installed, and I have tried various things regarding pointers and all sorts of other poking around, but it seems to this has something to do with a NVCC .. 

if I go into the directory in question and do a make : 
[ 75%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

**nvcc fatal   : redefinition of argument 'std'**

CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:207 (message):
  Error generating
  /src/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o

libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: **\* [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:232: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: **\* [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2

I saw there was a discussion to upstream your changes into cpp-ethereum .. I wish you would help them do it. Anyway .. I see someone else was also trying to get help on this error on the ethereum forums, so I  know I am not the only one. 

Thanks
int.

**Comment by Genoil** [comment]
I'm not very good with Linux, but I do see that 'std'is defined with gnu99 in libethash and with c++11 in libethashcuda (both CMakelists.txt). On my reference Linux platform (Ubuntu 14.04) it compiles fine nevertheless. But it does need a fix.

**Comment by int03h** [comment]
Just to prove that CUDA Support does work. NOTE the required edit to fix it ..I also just used compute_52 because that's all I need... 

root@eth:/src/cpp-ethereum/build/libethash-cuda/CMakeFiles/ethash-cuda.dir# nano -w ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake

Change this : 
set(CUDA_NVCC_FLAGS --std=c++11;--disable-warnings;--ptxas-options=-v;-use_fast_math;-lineinfo;-gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_61,code=sm_61 ;; ) # list

To this : 
set(CUDA_NVCC_FLAGS --disable-warnings;--ptxas-options=-v;-use_fast_math;-lineinfo;-arch=compute_52,code=sm_52;; ) # list


genminer-cl --list-devices  -G
Genoil's ethminer 0.9.41-genoil-1.1.3
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nerdralph, RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 970
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294246400
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073561600
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[1] GeForce GTX 970
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294770688
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073692672
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024


OpenCL 1.1.3  ( 2x NVIDIA 970s ) 

Trial 1... 35913728
Trial 2... 35738965
Trial 3... 35826346
Trial 4... 35738965
Trial 5... 35826346
min/mean/max: 35738965/35808870/35913728 H/s
inner mean: 23913358 H/s
 
genminer-cuda --list-devices  -U
Genoil's ethminer 0.9.41-genoil-1.1.3
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nerdralph, RoBiK, tpruvot and sp_

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[CUDA]:
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 970
        Compute version: 5.2
        cudaDeviceProp::totalGlobalMem: 4294246400
[1] GeForce GTX 970
        Compute version: 5.2
        cudaDeviceProp::totalGlobalMem: 4294770688

Cuda 
Trial 1... 37049685
Trial 2... 36350634
Trial 3... 37049685
Trial 4... 36700160
Trial 5... 36350634
min/mean/max: 36350634/36700159/37049685 H/s
inner mean: 24583281 H/s

**Comment by MrR0bo7** [comment]
I had the same error and for me the solution was to remove:
`;arch=compute_61,code=sm_61`

So the line in my ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake is:
`set(CUDA_NVCC_FLAGS --std=c++11;--disable-warnings;--ptxas-options=-v;-use_fast_math;-lineinfo;-gencode;arch=compute_20,code=sm_20;-gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode ;; ) # list`

(Building for GTX 750 Ti on Ubuntu 14.04)

**Comment by int03h** [comment]
Your card dosnt suppport 60 and 61... use the graph provided .. https://en.wikipedia.org/wiki/CUDA ..
