### ISSUE TITLE
Exception thrown in Worker thread: invalid string position at v1.1.5

### ISSUE THREAD

**Issue by miningpoolhub** [Genoil/cpp-ethereum#56]
v1.1.5 crashes with weird statement.

![genoil115](https://cloud.githubusercontent.com/assets/6733455/16169408/2b8685f8-3567-11e6-8ffc-2a984bc1f930.jpg)

Any idea?

**Comment by Genoil** [comment]
Fixed in 1.1.6. Thanks!
