### ISSUE TITLE
setting grid/block size in 1.1.5 will throw cuda error

### ISSUE THREAD

**Issue by kruisdraad** [Genoil/cpp-ethereum#57]
ethminer -U -t 6 -F http://127.0.0.1:8080/MINER2 --cuda-block-size 256 --cuda-grid-size 16384

results in : `Cuda error in func 'ethash_generate_dag' at line 133 : invalid argument.`

I've tried loads of combinations, any attempt to set them results into this error. Using defaults do work fine

**Comment by Genoil** [comment]
i think this is simply too much. does it still happen when you lower the numbers (keep powers of 2 for block size)?

**Comment by kruisdraad** [comment]
yeah, any kind of change of de default will result in the Cuda Errors

**Comment by Genoil** [comment]
as you know, don't have cuda cards today :)
