### ISSUE TITLE
Have ethminer to die when stops mining

### ISSUE THREAD

**Issue by kruisdraad** [Genoil/cpp-ethereum#58]
At some points the ethminer will start to spit out 0MH/s and all the times i found them where at 2 points:

1 at startup, when DAG isn't loaded yet
2. at problems, where the miner actually died (driver, overclocking, isuses ,etc)

Would it be possible to add a guardian that would make ethminer really die, as it seems the main loop of mining does continue, but it cannot spawn childs or something like that? The guardian could kick in after DAG is loaded, perhaps option with --guardian

**Comment by Genoil** [comment]
Sure. Can you C++? ;-)

**Comment by kruisdraad** [comment]
I wish, but sadly i am limited to PHP. I have two pretty nice projects going on. If i could help i'd really did, i've written a PHP wrapper dat spawns ethminer as a child and restarts it when its nothing doing stuff anymore ... but its really ugly and not really efficient.

**Comment by kruisdraad** [comment]
now keep in mind i know jack about C, but here is a pitch:

in "libethcore/Miner.h" at line 104 (where i think is a function that returns the solution stats) i thought perhaps you could write this to a state file (perhaps add more there in a nice json?)

Something in the line of  (and i googled most stuff)

```
FILE *f = fopen("/tmp/$processname.$processpid", "w");
if (f != NULL)
{
    const char *status =  "[A" << s.getAccepts() << "+" << s.getAcceptedStales() << ":R" << s.getRejects() << "+" << s.getRejectedStales() << ":F" << s.getFailures() << "]";
    fprintf(f, status);

    return status
}
```

moving the hashing rate into that section makes it nicely parseable too and again, prolly best to have an option for this, e.g. --stats-file=bla :)


secondly in the doFarm (ethminer) while running you call f.resetMiningProgress and i think that this is the part that finally results in 0MH/s outputs. how about addingvalues:

value : monitoringActiveCounter, a counter to fill nonZero MH/s (perhaps limit to 10 so safe on RAM?)
value : monitoringActive, which is set to true after more then 10x MH/s rates nonZero
value : dieCounter, a counter that fill Zero MH/s moments
value : dieThreshold, which is default 10 ... so 10x 0MH/s should kill the process

again just pitching here, i know nothing about C :)

**Comment by Genoil** [comment]
why don't you just dive in there :), fork it and try some stuff out. You seem to have plenty more time for this currently than me :)

en de groeten he ;)
