### ISSUE TITLE
Suggest to load kernel from the external file format as 

### ISSUE THREAD

**Issue by mkimid** [Genoil/cpp-ethereum#59]
First, thank you for the great updates and your job.
For the kernel expert user, I wish the kernel can loaded from the disk instead,
I have tried minor modify with the original ethminer, and I am using without any problem now. 

**Modification Suggest  '/libethash-cl/ethash_cl_miner.cpp'**

LINE #41 - COMMENT
`
// #include "ethash_cl_miner_kernel.h"
`

LINE #405 - Change as below

The original code is 

`
string code(ETHASH_CL_MINER_KERNEL, ETHASH_CL_MINER_KERNEL + ETHASH_CL_MINER_KERNEL_SIZE);
`

The suggested code for this line 

```
 		ifstream file("ethminer.cl", ios::in | ios::binary | ios::ate);
 		if (!file.is_open()) {
 			ETHCL_LOG("Can not load 'ethminer.cl'");
 			return false;
 		}
 		file.seekg(0, ios::end);
 		size_t ETHASH_CL_MINER_KERNEL_SIZE = file.tellg();
 		if (ETHASH_CL_MINER_KERNEL_SIZE < 256) {
 			ETHCL_LOG("Invalid kernel file size = " << ETHASH_CL_MINER_KERNEL_SIZE);
 			return false;
 		}
 		string code(ETHASH_CL_MINER_KERNEL_SIZE, ' ');
 		file.seekg(0, ios::beg);
 		file.read(&code[0], ETHASH_CL_MINER_KERNEL_SIZE);
 		file.close();
```

and, Rename 'ethash_cl_miner_kernel.cl' as 'ethmier.cl' 

Regards

**Comment by Genoil** [comment]
Hi, thank and thanks for your suggestion. However, it's unlikely that I will implement this for regular CL kernels, because people that make useful tweaks to the current kernel are very likely to be capable of building ethminer from source. Perhaps I'll include something that will load @wolf9466 GCN binaries for the few that are lucky to own it.

**Comment by wolf9466** [comment]
Thanks for that, if you do it, @Genoil - my current format is ethash-<name>.bin, where <name> is the chip name (I think the same as CL_DEVICE_NAME.)

**Comment by Genoil** [comment]
@wolf9466 now that you mention it, I must have half of the code loitering around in some deserted branch somewhere when I got all paranoid about CodeXL potentially doing a different compile than ethminer :). So I started loading bins instead. Not that it ultimately made any difference.

**Comment by wolf9466** [comment]
@Genoil It won't - CodeXL and ethminer use the same calls into the driver to do it. By the by, I finished an implementation using NO LDS whatsoever :3

**Comment by mkimid** [comment]
@Genoil Thank you for your answer, I feel that is so much time killing for the testing of modified or updated kernel, in AMD GPU, as you know, the hashing speed is related with the global memory access and memory channel conflict. In your ethminer can create DAG in GPU memory directly, I believe it is really good idea. and possibly, the DAG itself can be optimized with kernel interleaving together. All codes can be implemented with just Kernel only. If there is no special reason, I hope you can support BIN and/or CL together. and, I believe can get the best result when more person review the code ^^,

**Comment by mkimid** [comment]
@wolf9466 CodeXL and Inline complier will not generate the same binary code. I do not know why, in default, they use the difference compiler option and debug level code.

**Comment by wolf9466** [comment]
@mkimid Assuming you're not doing something dumb like using different defines, yes, they will.

**Comment by mkimid** [comment]
@wolf9466 actually, I just using the simple bare code for it. anyway, thank you for your advice.
