### ISSUE TITLE
cmake fails: Unknown CMake command "eth_install_executable"

### ISSUE THREAD

**Issue by sebastianst** [Genoil/cpp-ethereum#6]
I run

    % cd cpp-ethereum
    % mkdir build
    % cd build
    % cmake .. -DGUI=0 -DETHASHCL=1

and cmake fails with

```
CMake Error at CMakeLists.txt:48 (eth_install_executable):
  Unknown CMake command "eth_install_executable".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.4)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/XXX/cpp-ethereum/CMakeFiles/CMakeOutput.log".
```
even though `cmake/EthExecutableHelper.cmake` contains `eth_install_executable`.

This is after a fresh clone of this repo today.

**Comment by Genoil** [comment]
Try using -DBUNDLE=miner or =cudaminer. Note that the latter is currently broken for Compute 5.2

**Comment by sebastianst** [comment]
Thanks, cmake now runs successfully with the `-DBUNDLE={,cuda}miner` options.
Do you think you could drop a little `BUILD` file with build instructions in the root of the repo? Since the upstream wiki has gone offline, it would be helpful to have a short summary of how to build this repo.
Or do you plan to migrate to the new webthree codebase any way?

What is _Compute 5.2_?
