### ISSUE TITLE
Compile issue with Debian Stretch

### ISSUE THREAD

**Issue by AltFreq** [Genoil/cpp-ethereum#60]
Im trying to compile cudaminer but am currently coming accross annoying errors.
Operating System: Linux-x86_64 - Debian Stretch
GPU - Nvidia 1080 GTX
GPU Drivers -367.27

I have tried with both CUDA toolkit 7.5 and 8.0 and am getting the same error on compile
These are the commands I run
mkdir build
cd build
cmake -DBUNDLE=cudaminer ..
make -j8

```
[ 33%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieCommon.cpp.o
[ 35%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Log.cpp.o
[ 37%] Linking CXX shared library libethash-cl.so
[ 37%] Built target ethash-cl
[ 39%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake:207 (message):
  Error generating
  /home/user/cpp-ethereum/test/libethash-cuda/CMakeFiles/ethash-cuda.dir//./ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o


libethash-cuda/CMakeFiles/ethash-cuda.dir/build.make:63: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o' failed
make[2]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o] Error 1
CMakeFiles/Makefile2:320: recipe for target 'libethash-cuda/CMakeFiles/ethash-cuda.dir/all' failed
make[1]: *** [libethash-cuda/CMakeFiles/ethash-cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 41%] Building CXX object libdevcore/CMakeFiles/devcore.dir/StructuredLogger.cpp.o
[ 43%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieDB.cpp.o
[ 45%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonJS.cpp.o
[ 47%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonIO.cpp.o
[ 50%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Base64.cpp.o
[ 52%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Common.cpp.o
[ 54%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonData.cpp.o
[ 56%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RLP.cpp.o
[ 58%] Linking CXX shared library libethstratum.so
[ 58%] Built target ethstratum
[ 60%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 62%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o
[ 64%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FixedHash.cpp.o
[ 66%] Linking CXX shared library libdevcore.so
[ 66%] Built target devcore
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

There are a few warnings earlier in the log about depreciation and some "note: declared here"
if you would like me to post whole log.

**Comment by sardylan** [comment]
I temporary resolved adding **-D_FORCE_INLINES** to **CMAKE_CXX_FLAGS** and removing all **-std=c++11** from generated Makefiles (after running _cmake_ and before running _make_), especially in _libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o.cmake_
Newer version of compilers and drivers perhaps have different behaviour managing std flags...

**Comment by int03h** [comment]
[ 39%] Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.o
nvcc fatal   : redefinition of argument 'std' 

this is "normal" behavious .. 

you can fix this by using one of the pull requests .. 
like this https://github.com/Genoil/cpp-ethereum/pull/76

**Comment by axelsimon** [comment]
Hello,
I'm also hitting a problem compiling on Debian Stretch. CUDA only supports gcc versions up to 5.3 and `make` gives this error:
```
 #error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
```

I've tried adding gcc-5 as an alternative (using this [helpful page](https://blog.mixable.de/nvidia-cuda-on-ubuntu-unsupported-gnu-version-gcc-versions-later-than-5-are-not-supported/)) however, while Stretch still has gcc-5, it doesn't have g++-5, which still leads to errors (`cc: error trying to exec 'cc1plus': execvp: No such file or directory`).

Any clues? Thanks.
