### ISSUE TITLE
improvement: change default global-work to 16k

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#61]
I think part of the reason why some people find Claymore's miner faster is that they don't change the default work values.  16k global work generally gives a 3-5% improvement in hashrate, and doesn't seem to have any downsides.

**Comment by Genoil** [comment]
Good point.

**Comment by Genoil** [comment]
even though i cleaned my old 7950 and gave it fresh thermal paste, i can't get the card stable with this setting. it's too much for a default setting i'm afraid.

**Comment by jch9678** [comment]
According to dlhenkey and wolf, 16k will give you many more stale shares.
