### ISSUE TITLE
farm failover works, but does not fall back to primary

### ISSUE THREAD

**Issue by kruisdraad** [Genoil/cpp-ethereum#64]
Once the primary farm address fails it correctly falls back to the backup host (--farm-failover) however it will never fall back to its primary.

If you backup fails it will endlessly retry on the backup address and not the primary address. If the secundairy fails perhaps retry primary?

perhaps a non-blocking check for the main farm address and once its back online switch back to that address.

**Comment by Genoil** [comment]
the idea was indeed to have it go back to the primary address once the failover was failing. i thought it already worked like that..

then another improvement would be to try the primary address occasionally while you're on the back up. but that's a different functionality, not a bug like you describe here. i'll have a look, thx.
