### ISSUE TITLE
System Fault on CUDA mining

### ISSUE THREAD

**Issue by smarrazzo** [Genoil/cpp-ethereum#66]
If you have 2 or more Nvidia card (TITAN Black and Titan-X for me).
OS : ubuntu 15

If i run only one instance for all GPU, there is a system fault issue when miner submit solution.
But if i run one instance of ethermine for each card, their is no issue .
I think this is due to the sync between GPU.

**Comment by Genoil** [comment]
is this still an issue? which version are you running? which os?
