### ISSUE TITLE
small opencl code change

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#68]
No need to zero index 8 since it gets set after the loop.
<pre>
diff --git a/libethash-cl/ethash_cl_miner_kernel.cl b/libethash-cl/ethash_cl_min
index 390a021..95d7686 100644
--- a/libethash-cl/ethash_cl_miner_kernel.cl
+++ b/libethash-cl/ethash_cl_miner_kernel.cl
@@ -348,7 +348,7 @@ __kernel void ethash_search(

 static void SHA3_512(uint2* s, uint isolate)
 {
-       for (uint i = 8; i != 25; ++i)
+       for (uint i = 9; i != 25; ++i)
        {
                s[i] = (uint2){ 0, 0 };
        }
</pre>

**Comment by nerdralph** [comment]
forgot to quote:
'diff --git a/libethash-cl/ethash_cl_miner_kernel.cl b/libethash-cl/ethash_cl_min
index 390a021..95d7686 100644
--- a/libethash-cl/ethash_cl_miner_kernel.cl
+++ b/libethash-cl/ethash_cl_miner_kernel.cl
@@ -348,7 +348,7 @@ __kernel void ethash_search(

 static void SHA3_512(uint2* s, uint isolate)
 {
-       for (uint i = 8; i != 25; ++i)
+       for (uint i = 9; i != 25; ++i)
        {
                s[i] = (uint2){ 0, 0 };
        }
'

**Comment by nerdralph** [comment]
Forgot to quote the diff text.
`diff --git a/libethash-cl/ethash_cl_miner_kernel.cl b/libethash-cl/ethash_cl_min
index 390a021..95d7686 100644
--- a/libethash-cl/ethash_cl_miner_kernel.cl
+++ b/libethash-cl/ethash_cl_miner_kernel.cl
@@ -348,7 +348,7 @@ __kernel void ethash_search(

 static void SHA3_512(uint2* s, uint isolate)
 {
-       for (uint i = 8; i != 25; ++i)
+       for (uint i = 9; i != 25; ++i)
        {
                s[i] = (uint2){ 0, 0 };
        }
`

**Comment by Genoil** [comment]
this will go into 1.1.8 thanks
