### ISSUE TITLE
--stratumfailover not working

### ISSUE THREAD

**Issue by kruisdraad** [Genoil/cpp-ethereum#69]
While passing options this works:

`miner@solominer:~$ ethminer -G -FS 1.1.1.1:1`

but this doesnt:

`ethminer -G --failover-stratum 1.1.1.1:1`

it results in 

> Invalid argument: --failover-stratum

however the help page shows:

> -FS, --failover-stratum <host:port>  Failover stratum server at host:port

i copy pasted the names, so it looks like a argument passing issue?

**Comment by Genoil** [comment]
typo.. should be --stratum-failover. thx for noticing
