### ISSUE TITLE
cleaner copy for dag generation

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#70]
<pre>
diff --git a/libethash-cl/ethash_cl_miner_kernel.cl b/libethash-cl/ethash_cl_min
index 390a021..54027bd 100644
--- a/libethash-cl/ethash_cl_miner_kernel.cl
+++ b/libethash-cl/ethash_cl_miner_kernel.cl
@@ -227,12 +227,14 @@ typedef struct
 } hash32_t;

 typedef union {
+       uint16   vec;
        uint     words[64 / sizeof(uint)];
        uint2    uint2s[64 / sizeof(uint2)];
        uint4    uint4s[64 / sizeof(uint4)];
 } hash64_t;

 typedef union {
+       uint16   vec;
        uint     words[200 / sizeof(uint)];
        uint2    uint2s[200 / sizeof(uint2)];
        uint4    uint4s[200 / sizeof(uint4)];
@@ -348,7 +350,7 @@ __kernel void ethash_search(

 static void SHA3_512(uint2* s, uint isolate)
 {
-       for (uint i = 8; i != 25; ++i)
+       for (uint i = 9; i != 25; ++i)
        {
                s[i] = (uint2){ 0, 0 };
        }
@@ -363,7 +365,9 @@ __kernel void ethash_calculate_dag_item(uint start, __global
        if (node_index > DAG_SIZE * 2) return;

        hash200_t dag_node;
-       copy(dag_node.uint4s, g_light[node_index % LIGHT_SIZE].uint4s, 4);
+       //copy(dag_node.uint4s, g_light[node_index % LIGHT_SIZE].uint4s, 4);
+       dag_node.vec = g_light[node_index % LIGHT_SIZE].vec;
+
        dag_node.words[0] ^= node_index;
        SHA3_512(dag_node.uint2s, isolate);

@@ -375,5 +379,6 @@ __kernel void ethash_calculate_dag_item(uint start, __global
                }
        }
        SHA3_512(dag_node.uint2s, isolate);
-       copy(g_dag[node_index].uint4s, dag_node.uint4s, 4);
+       //copy(g_dag[node_index].uint4s, dag_node.uint4s, 4);
+       g_dag[node_index].vec = dag_node.vec;
 }
</pre>

It doesn't seem to be any faster, but I think assigning one vector to another is cleaner, and in theory the OpenCL complier should auto-vectorize it (i.e. a simd-16 assignment of int32s).

**Comment by Genoil** [comment]
The best way to make it faster is to coalesce the reads from the cache. The CUDA kernel already has that, but uses warp shuffles which OpenCL doesn't have. So you have to use shared memory.

**Comment by nerdralph** [comment]
I don't know enough about GCN to agree or disagree... yet.

**Comment by wolf9466** [comment]
GCN doesn't have vector regs. Sorry. It'll get serialized as 32-bit.

**Comment by Genoil** [comment]
didn't know opencl had a uint16 though. looks clean. altough slightly confusing with your average 16-bit unsigned integer.

**Comment by wolf9466** [comment]
It does. And a ulong16.

**Comment by nerdralph** [comment]
@Genoil I noticed the similarity to unit16_t when I was writing it, but only because I've done a lot of programming on 8-bit MCUs (mostly AVR).

**Comment by nerdralph** [comment]
@wolf9466 Each SIMD in a CU has 64KB for VGPRs, and I thought they are partitioned as 16 sets per SIMD, so 256 registers * 32bits (4 bytes) = 16KB.  I still haven't figured out how the other 48K is used though, so my interpretation may well be wrong.  I'm looking at figure 3:
https://www.amd.com/Documents/GCN_Architecture_whitepaper.pdf

**Comment by wolf9466** [comment]
You're thinking about it wrong. You have 64KiB worth of VGPRs, v0 - v255. You still access via 32-bit registers, though. And just because you HAVE 256 VGPRs doesn't mean you want to USE all of them, because ideally you want more than one wave in flight (usually.)

**Comment by wolf9466** [comment]
Remember VGPRs are private to a work-item, and there are 64 work-items in a wavefront.

**Comment by nerdralph** [comment]
@wolf9466 Thanks. Now I remember reading the 64 work-items/wavefront before,  so 256 VGPRs * 4 bytes each * 64 work-items = 64KB.
My brain is still learning how to visualize multi-threaded SIMD execution flow...

**Comment by wolf9466** [comment]
It's not quite SIMD. It's SIMT - single instruction, multiple thread.

**Comment by nerdralph** [comment]
From the white paper I linked above, they call it SIMD:
"In GCN, each CU includes 4 separate SIMD units for vector processing. Each of these SIMD units simultaneously executes a single operation across 16 work items"
So when the kernel executes a v_xor_b32 instruction on a SIMD unit, it does it for 16 work items simultaneously (assuming the execute mask is all 1s).

Interestingly the Sea Islands ISA describes it in a way that agrees with your SIMT definition:
"The Execute mask (64-bit) determines which threads in the vector are executed: 1 = execute, 0 = do not execute."

**Comment by wolf9466** [comment]
I manipulate the EXEC mask all the time to ensure only certain threads do something, but yeah.

**Comment by Genoil** [comment]
I just optimized the dag gen on opencl from 7.1s on a 7950 (current DAG epoch) to 4.1s. Coalescing the reads (4-way) gave only 0.5s..much less than the impact on CUDA (+40%).

**Comment by nerdralph** [comment]
Can't wait to see the commit...
So I found the DAG generation is a great way to learn and tweak the performance since it does both sha512 and lots of memory IO, while being small enough to understand what it is doing after reading the code a couple times.

**Comment by Genoil** [comment]
then don't wait for the commit and see if you can make it faster :). in hindsight, the coalescing does almost nothing when I leave the other optimizations on. those are much simpler.

**Comment by nerdralph** [comment]
Got a slight speedup: it's now 3-4s on R7 370 @1150/1500.
<pre>
static void SHA3_512(uint2* s, uint isolate, __local uint2* zeros)
{
        for (uint i = 9; i != 25; i+=2)
        {
                // interleave vector and LDS operations for
                // better wave occupancy
                s[i] = *zeros;
                s[i+1] = (uint2){ 0, 0 };
        }
        s[8].x = 0x00000001;
        s[8].y = 0x80000000;
        keccak_f1600_no_absorb(s, 8, isolate);
}

__kernel void ethash_calculate_dag_item(uint start, __global hash64_t const* g_light, __global hash64_t * g_dag, uint isolate)
{
        __local uint2 zeros;
        uint const node_index = start + get_global_id(0);
        zeros = (uint2){ 0, 0 };
        if (node_index > DAG_SIZE * 2) return;
</pre>

The logic behind the change is that the original code was likely compiled to a series of v_mov_b32 v, 0 instructions.  I create a 8-bytte buffer in the LDS and initialize it to zero.  The "s[i] = *zeros;" line should compile to ds_read_b64.  Since the CU can simultaneously execute a VALU and a LDS instruction on 2 different waves, this allows for more concurrency.

**Comment by Genoil** [comment]
Nice. In my current code I don't set the zeros any longer, because I optimized the first keccak round, so that it is no longer required to set them.

**Comment by nerdralph** [comment]
" I optimized the first keccak round, so that it is no longer required to set them."
The ideal optimization; when you find code that doesn't even need to be executed!  Now I really want to see your new commits.

**Comment by Genoil** [comment]
I can't yet because I'm in the middle of fixing an issue that has been in the code since its Tim Hughes wrote it; on GCN 1.1+ it gets only 2 waves in flight (not 3 as with GCN 1.0). Almost fixed it, still two VGPRS short.

As for unrolling the first/last round of Keccak, just look at the CUDA code, it has all that stuff already for months.

**Comment by barry8212** [comment]
Hi Genoil

I have an idea regarding dag file. I am not sure how the dag file works but would like to discuss the idea with you. Do you maybe have skype or any other way to communicate. Would be appreciated if you can assist me

**Comment by Genoil** [comment]
hi @barry8212, sorry for the late reply. please contact me on gitter. if you still want to discuss the idea.
