### ISSUE TITLE
Building error with pthread

### ISSUE THREAD

**Issue by NicolasCARPi** [Genoil/cpp-ethereum#79]
Hello,

I am trying to build latest version from master branch on Archlinux 64bits. After installing all the needed dependencies, I managed to create a Makefile with the command : 

``` sh
mkdir build; cd build
cmake -DBUNDLE=cudaminer ..
```

I have an NVIDIA card and want to try mining with it.

Now when I run the command `make`, it outputs this (in CMakeFiles/CMakeError.log) : http://pastebin.com/i0wmesjY

I really tried hard to google my way out of this, but failed. I should add that I'm not familiar with CMAKE, but understand the basic principle (generate a Makefile, rite?).

Anyway, if someone can help me troubleshooting this issue I'd be glad :)

Regards,
~Nico

**Comment by chadgrant** [comment]
Same issue on windows build, following instructions : 

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

**Comment by chadgrant** [comment]
my issue I resolved by installing CUDA (duh) and making sure the CUDA env vars were set
