### ISSUE TITLE
Make a Docker image

### ISSUE THREAD

**Issue by NicolasCARPi** [Genoil/cpp-ethereum#80]
Hello,

It looks like you don't have a proper docker image. As compilation is not trivial, it would be great to have such an image.

I'd be willing to make one, but want to know before if this would be interesting or if you already tried.

**Comment by nerdralph** [comment]
I've been looking into making a statically-linked binary.  If that doesn't work out, I'll probably do a snap package which is based on docker.
https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/

**Comment by NicolasCARPi** [comment]
Why not both? :)

**Comment by nerdralph** [comment]
Static linux binary just finished:
https://github.com/Genoil/cpp-ethereum/issues/87
