### ISSUE TITLE
lots of code fixes

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#82]
I forked the 110 branch and did a bunch of updates.
https://github.com/nerdralph/ethminer-nr/tree/110

I cleaned up EthStratumClientV2, removed all mutexes, and improved the stale submission tracking, and fixed the nuisance "unknown error" on receiving a new job that wasn't really an error.
For end users the biggest difference should be improved stability (no chance for mutex deadlock), and timing of share submissions so you can tell if your pool is slow:
stratum  B-) Submitted and accepted in 37 ms.

See the diff for full details:
https://github.com/Genoil/cpp-ethereum/compare/110...nerdralph:110

p.s. failover isn't yet robust.  I need to drop the shares when there is no pool connection.  Hope to have a fix in place, tested, and pushed to the repo within 24hrs.

**Comment by nerdralph** [comment]
Just pushed the changes to handle failed writes on share submit.  Failover testing passed.

**Comment by Genoil** [comment]
Cool. If you got the work time-out working again, I suggest we (you, I'm on holiday ;-) ) completely remove the async client. I'm home in between two trips next week, may have time to merge and release as 1.1.8.

**Comment by Genoil** [comment]
Alternatively, just release yourself as it will be weeks before I get back.

**Comment by nerdralph** [comment]
The boost async timer callbacks require another thread calling run() to work, which would mean adding back async code to the sync (V2) implementation.  My "solution" is to let the TCP layer handle the timeouts/failure.  I've added code to enable keepalive on the socket, though to get reasonably quick failover it was necessary to tweak the kernel tcp settings with sysctl.  I plan to document the details shortly.
I'm also not convinced the work timeout was a good idea in the first place.  Given the random distribution of block times. even with a 5-minute work timeout you'll probably get false-positive failovers a couple times a day.  From looking at blockchain data, it seems normal to have a block take 50-60 seconds about every 10 minutes.

**Comment by Genoil** [comment]
Yeah well in that case, just leave it out and drop the async client anyway.

**Comment by nerdralph** [comment]
Sounds good.  When I started looking at the async and sync code, I was thinking it was quite a mess and couldn't figure out why you'd code it that way.  Then I found your comment in MinerAux.h:
"this is very ugly, but if Stratum Client V2 tunrs out to be a success, V1 will be completely removed anyway"

**Comment by nerdralph** [comment]
Just pushed the MinerAux.h commit.  As with the earlier changes, tested on Linux but not Windoze.

**Comment by chuckrussell1958** [comment]
Thanks for the cleanups. Any idea when this will be merged into a 1.1.x release?

**Comment by chuckrussell1958** [comment]
Probably ought to punch up the Read.me on this. I'd be happy to help.

**Comment by nerdralph** [comment]
@chuckrussell1958 I was planning to do that, and finally got around to it.

--- a/README.md
+++ b/README.md
@@ -5,11 +5,11 @@ What is ethminer-0.9.41-genoil-1.x.x?
 Formerly known as Genoil's CUDA miner, ethminer-0.9.41-genoil-1.x.x is a fork o

 - realistic benchmarking against arbitrary epoch/DAG/blocknumber
-- custom DAG storage directory
-- auto DAG directory cleanup
+- fast on-GPU DAG creation uses no disk space
 - stratum mining without proxy
 - OpenCL devices picking
 - farm failover (getwork + stratum)
+- submits stale shares for previous block

 ### Usage

**Comment by chuckrussell1958** [comment]
I've built your 1.1.0 fork and will test it this afternoon.

**Comment by chuckrussell1958** [comment]
I'm building your 1.1.0 fork and will run it in production tonight.

**Comment by UberEth** [comment]
@nerdralph  - consistent cored dumps on your fork. I noticed that you've committed recently (after my build). Let me know what you need from me for debug purposes.

**Comment by nerdralph** [comment]
Just finished cleaning up some dependencies.  mesa-common-dev, libmicrohttp-dev, libgmp-dev, ibcurl4-gnutls-dev no longer needed.
README install instructions updated accordingly.

**Comment by nerdralph** [comment]
There was a divide by zero bug in the new stats code that was only there
for an hour or so.  Just do a pull.

On Jul 25, 2016 17:40, "UberEth" <notifications@github.com> wrote:

@nerdralph <https://github.com/nerdralph> - consistent cored dumps on your
fork. I noticed that you've committed recently (after my build). Let me
know what you need from me for debug purposes.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Genoil/cpp-ethereum/issues/82#issuecomment-235077674>,
or mute the thread

**Comment by UberEth** [comment]
@nerdralph  - NEW BUILD - CORE DUMP - console logs for your review:

OPENCL#0: 96%
  m  17:24:32|ethminer  9786 27962 23767 = 61516Khs [A0+0:R0+0:F0]
  m  17:24:33|ethminer  26563 26563 27962 = 81089Khs [A0+0:R0+0:F0]
  m  17:24:33|ethminer  26563 26563 26563 = 79691Khs [A0+0:R0+0:F0]
  m  17:24:34|ethminer  27962 27962 27962 = 83886Khs [A0+0:R0+0:F0]
  m  17:24:35|ethminer  26563 26563 26563 = 79691Khs [A0+0:R0+0:F0]
  m  17:24:36|ethminer  26563 27962 27962 = 82487Khs [A0+0:R0+0:F0]
  m  17:24:36|ethminer  27962 26563 26563 = 81089Khs [A0+0:R0+0:F0]
  m  17:24:37|ethminer  26563 27962 26563 = 81089Khs [A0+0:R0+0:F0]
  m  17:24:38|ethminer  26563 26563 27962 = 81089Khs [A0+0:R0+0:F0]
  ℹ  17:24:38|stratum  Received new job #0x9f4a29
  ℹ  17:24:38|OCLminer0  set work; seed: #9af06ef9, target:  #0000002af31d
  ℹ  17:24:38|OCLminer1  set work; seed: #9af06ef9, target:  #0000002af31d
  ℹ  17:24:38|OCLminer2  set work; seed: #9af06ef9, target:  #0000002af31d
  ℹ  17:24:39|OCLminer1  Solution found; Submitting to eth.pool.minergate.com ...
  m  17:24:39|ethminer  28244 26479 24713 = 79437Khs [A0+0:R0+0:F0]
  ℹ  17:24:39|stratum  B-) Submitted and accepted in 113 ms.
  ℹ  17:24:39|OCLminer2  Solution found; Submitting to eth.pool.minergate.com ...
  m  17:24:39|ethminer  26563 27962 26563 = 81089Khs [A1+0:R0+0:F0]
  ℹ  17:24:40|stratum  B-) Submitted and accepted in 113 ms.
  m  17:24:40|ethminer  27962 26563 27962 = 82487Khs [A2+0:R0+0:F0]
  m  17:24:41|ethminer  26563 26563 26563 = 79691Khs [A2+0:R0+0:F0]
  m  17:24:42|ethminer  26563 27962 27962 = 82487Khs [A2+0:R0+0:F0]
  ℹ  17:24:42|OCLminer0  Solution found; Submitting to eth.pool.minergate.com ...
  m  17:24:42|ethminer  27962 26563 26563 = 81089Khs [A2+0:R0+0:F0]
  ℹ  17:24:43|stratum  B-) Submitted and accepted in 112 ms.
  ℹ  17:24:43|OCLminer2  Solution found; Submitting to eth.pool.minergate.com ...
  m  17:24:43|ethminer  26563 27962 26563 = 81089Khs [A3+0:R0+0:F0]
  ℹ  17:24:43|OCLminer0  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  17:24:43|stratum  B-) Submitted and accepted in 10 ms.
  ℹ  17:24:43|stratum  B-) Submitted and accepted in 122 ms.
  ℹ  17:24:44|OCLminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  17:24:44|stratum  B-) Submitted and accepted in 113 ms.
  m  17:24:44|ethminer  26563 26563 27962 = 81089Khs [A6+0:R0+0:F0]
  m  17:24:45|ethminer  26563 27962 26563 = 81089Khs [A6+0:R0+0:F0]
  ℹ  17:24:45|OCLminer0  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  17:24:45|stratum  Received new job #0x2837b9
  ℹ  17:24:45|OCLminer0  set work; seed: #9af06ef9, target:  #00000034abdc
  ℹ  17:24:45|OCLminer1  set work; seed: #9af06ef9, target:  #00000034abdc
  ℹ  17:24:45|OCLminer2  set work; seed: #9af06ef9, target:  #00000034abdc
ethminer: src/lib_json/json_value.cpp:1102: const Json::Value& Json::Value::operator[](Json::Value::ArrayIndex) const: Assertion `type_ == nullValue || type_ == arrayValue' failed.
./startnerdminer.sh: line 15:  1018 Aborted

**Comment by nerdralph** [comment]
@UberEth That's related to my fix of the "unknown error" messages.  Minergate must be sending different than mph and coinmine.pl
For now change line 257 back to the way it was:
if (error.isArray())
instead of error.size().
https://github.com/nerdralph/ethminer-nr/blob/110/libstratum/EthStratumClientV2.cpp#L257

I took a quick look at minergate and it doesn't look like an open pool, so if I can't figure out what they are sending back I'll get you to turn on debug logging so I can see the exact json message received.

**Comment by nerdralph** [comment]
@UberEth 
There's a bug in jsoncpp 0.6.0.  There was nothing being done with the json errors other than printing the "unknown error" message, so I've just commented out the code until one of the newer versions of jsoncpp can be tested.
I re-tested the commit against mph and coinmine, so give it a whirl.

**Comment by UberEth** [comment]
I recompiled per your suggestion and that fixed the bug - but the system hangs on stale commits. Any way to ship you a log or/debug.out? thx.

**Comment by nerdralph** [comment]
removing the -DNDEBUG will enable debugging output, but that will give a lot more output than is necessary.
If you change 'cdebug' to 'cnote' on lines 92 and 504 of EthStratumClientV2.cpp and rebuild, that should give me enough to figure out what's going on without polluting the output.
https://github.com/nerdralph/ethminer-nr/blob/110/libstratum/EthStratumClientV2.cpp#L504

**Comment by nerdralph** [comment]
After looking at the json error parsing a bit more, I figured out the error was in the stratum code.  In fact it was likely a small memory leak too for every json message received over stratum, and has been there since at least 1.0.7.  Fixed and pushed now.
I'll also try a couple different pools besides mph and coinmine to see if I can reproduce the stale share problem you are seeing.

**Comment by UberEth** [comment]
I suspected a memory leak somewhere, but it's tiny - I was monitoring mem usage and it is negligible. It appears that mining speed/throughput drops gradually, I'm seeing hash rates drop 10-20% just before it craps the bed. The miner goes to fetch a new unit of work / job, then hangs and afterwards 'stale share' errors appear and she's hosed.

**Comment by UberEth** [comment]
See console logs leading up to stale shares - prob not all that helpful 

..
  ℹ  22:03:40|openclminer1    Nonce: 0x7a71d1a4c8f9fe91
  ℹ  22:03:40|stratum  B-) Submitted and accepted.
  m  22:03:41|ethminer  Mining on PoWhash #a98e43ef : 72.70MH/s [A315+0:R4+0:F0]
  m  22:03:41|ethminer  Mining on PoWhash #a98e43ef : 69.91MH/s [A315+0:R4+0:F0]
  m  22:03:42|ethminer  Mining on PoWhash #a98e43ef : 71.30MH/s [A315+0:R4+0:F0]
  m  22:03:43|ethminer  Mining on PoWhash #a98e43ef : 72.70MH/s [A315+0:R4+0:F0]
  m  22:03:44|ethminer  Mining on PoWhash #a98e43ef : 71.30MH/s [A315+0:R4+0:F0]
  m  22:03:44|ethminer  Mining on PoWhash #a98e43ef : 71.30MH/s [A315+0:R4+0:F0]
  m  22:03:45|ethminer  Mining on PoWhash #a98e43ef : 71.30MH/s [A315+0:R4+0:F0]
  m  22:03:46|ethminer  Mining on PoWhash #a98e43ef : 69.91MH/s [A315+0:R4+0:F0]
  m  22:03:47|ethminer  Mining on PoWhash #a98e43ef : 74.10MH/s [A315+0:R4+0:F0]
  m  22:03:47|ethminer  Mining on PoWhash #a98e43ef : 71.30MH/s [A315+0:R4+0:F0]
  m  22:03:48|ethminer  Mining on PoWhash #a98e43ef : 71.30MH/s [A315+0:R4+0:F0]
  ℹ  22:03:48|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:03:48|openclminer2    Nonce: 0x307d85bf6f0db4f8
  ℹ  22:03:48|stratum  B-) Submitted and accepted.
  m  22:03:49|ethminer  Mining on PoWhash #a98e43ef : 69.91MH/s [A316+0:R4+0:F0]
  ℹ  22:03:49|stratum  Received new job #0x303011
  ℹ  22:03:50|openclminer0  set work; seed: #9af06ef9, target:  #00000014837f
  ℹ  22:03:50|openclminer1  set work; seed: #9af06ef9, target:  #00000014837f
  ℹ  22:03:50|openclminer2  set work; seed: #9af06ef9, target:  #00000014837f
  m  22:03:50|ethminer  Mining on PoWhash #3030115c : 0.00MH/s [A316+0:R4+0:F0]
  ℹ  22:03:50|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:03:50|openclminer1    Nonce: 0x6c4629af3ba85421
  ℹ  22:03:50|stratum  B-) Submitted and accepted.
  m  22:03:50|ethminer  Mining on PoWhash #3030115c : 69.91MH/s [A317+0:R4+0:F0]
  m  22:03:51|ethminer  Mining on PoWhash #3030115c : 71.30MH/s [A317+0:R4+0:F0]
  m  22:03:52|ethminer  Mining on PoWhash #3030115c : 69.91MH/s [A317+0:R4+0:F0]
  ℹ  22:03:52|stratum  Received new job #0xcd5f57
  ℹ  22:03:53|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:03:53|openclminer1    Nonce: 0x6c4629af4065b4bf
  ✘  22:03:53|openclminer1  Submitting stale solution.
  ℹ  22:03:56|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:03:56|openclminer2    Nonce: 0x52175076cbcd89fe
  ✘  22:03:56|openclminer2  Submitting stale solution.
  ℹ  22:04:15|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:15|openclminer1    Nonce: 0x6c4629af62691073
  ✘  22:04:15|openclminer1  Submitting stale solution.
  ℹ  22:04:18|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:18|openclminer1    Nonce: 0x6c4629af6641ba64
  ✘  22:04:18|openclminer1  Submitting stale solution.
  ℹ  22:04:24|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:24|openclminer1    Nonce: 0x6c4629af70406617
  ✘  22:04:24|openclminer1  Submitting stale solution.
  ℹ  22:04:34|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:34|openclminer2    Nonce: 0x5217507704cd7b49
  ✘  22:04:34|openclminer2  Submitting stale solution.
  ℹ  22:04:36|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:36|openclminer2    Nonce: 0x521750770740aa60
  ✘  22:04:36|openclminer2  Submitting stale solution.
  ℹ  22:04:36|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:36|openclminer2    Nonce: 0x5217507707850146
  ✘  22:04:36|openclminer2  Submitting stale solution.
  ℹ  22:04:36|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:36|openclminer2    Nonce: 0x5217507707a191b9
  ✘  22:04:36|openclminer2  Submitting stale solution.
  ℹ  22:04:39|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:39|openclminer1    Nonce: 0x6c4629af8634bf34
  ✘  22:04:39|openclminer1  Submitting stale solution.
  ℹ  22:04:44|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:44|openclminer1    Nonce: 0x6c4629af8ea82312
  ✘  22:04:44|openclminer1  Submitting stale solution.
  ℹ  22:04:50|openclminer1  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:50|openclminer1    Nonce: 0x6c4629af9729274f
  ✘  22:04:50|openclminer1  Submitting stale solution.
  ℹ  22:04:50|openclminer2  Solution found; Submitting to eth.pool.minergate.com ...
  ℹ  22:04:50|openclminer2    Nonce: 0x521750771c774c8c
  ✘  22:04:50|openclminer2  Submitting stale solution.

**Comment by nerdralph** [comment]
That doesn't look like a bug.  It looks like your first GPU hung. (miner0)
Since you commented on the "issue" about continuing to mine when one fails, I though you'd be able to figure it out.

**Comment by nerdralph** [comment]
And to make sure there's no more memory leaks, I've just finished a build with gcc-5.3 and -fsanitize=address,undefined. So far no errors/warnings after mining for 10 minutes.

**Comment by UberEth** [comment]
I'm not sure that it did hang. I realize that miner 1/2 are submitting the stale solutions - I aborted after only a few messages. What leads you to think miner0 is at fault. thx.

**Comment by UberEth** [comment]
I have gcc 4.9.2 installed

**Comment by nerdralph** [comment]
I already explained how to tell which GPU has failed:
https://github.com/Genoil/cpp-ethereum/issues/84

**Comment by nerdralph** [comment]
4.9.2 is fine, it just doesn't have the -fsanitize=undefined option.

**Comment by UberEth** [comment]
@nerdralph   getting intermittent Stratum errors: type can't be converted to String in latest build.  Followed by a "Reconnecting in 3 secnds'.

**Comment by nerdralph** [comment]
@UberEth Sounds like you're using a shitty pool.  Nevertheless, I've pushed a commit that just prints "unknown stratum error" and doesn't try to print out what was received in the json error field.

**Comment by UberEth** [comment]
You might be right. I'll test over at dwarfpool and get you some feedback.

**Comment by nerdralph** [comment]
Just did another push.  Terminal output has been streamlined, and DAG generation timing is now to the nearest millisecond:
<pre>
  ?  21:08:11|GPU0  DAG creation time: 3312 ms.
</pre>

**Comment by nerdralph** [comment]
Blog post discussing many of the improvements:
http://nerdralph.blogspot.ca/2016/07/improving-genoils-ethminer.html

**Comment by UberEth** [comment]
@nerdralph - question about the console log. What is the best way to redirect the console output to a file?  I didn't see a command line switch for that. Redirection of stdout only logs the initialization status. I'm not a c++ guy - so, it's hard trying to decipher log.cpp and log.h

thx.

**Comment by nerdralph** [comment]
@UberEth This is a generic Unix question.  Look up how to redirect stderr.

**Comment by UberEth** [comment]
ahh - I know how to do that of course - only tried stdout.

**Comment by Genoil** [comment]
Hey ralph, how have you been? is you 1.1.9nr running stable?

Is there any point in continuing work on the fork or did even the nvidia folks flock to Claymore now?

**Comment by nerdralph** [comment]
Welcome back.  Still been hacking the code here.  I have another patch I
tested for the past week that switches to the backup pool when N
consecutive share submits get no reply.
Claymore's CUDA is supposedly noticably slower than yours, but I saw a post
in the altcoin forum about a new CUDA-only miner that claims to be 10%
faster than yours.
Bob is still planning to upstream your changes, so you may consider that
reason to keep working on it.  I also want to keep working on the OCL
kernel.  I think it should be possible to get the VGPR use down to 64
without going to asm.  I also think 4 threads per hash instead of 8 should
be faster for low-end GPUs like the R7 370.

On Aug 29, 2016 06:01, "Genoil" <notifications@github.com> wrote:

Hey ralph, how have you been? is you 1.1.9nr running stable?

Is there any point in continuing work on the fork or did even the nvidia
folks flock to Claymore now?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Genoil/cpp-ethereum/issues/82#issuecomment-243070897>,
or mute the thread

**Comment by Genoil** [comment]
merged most (if not all) of this into 110. Thanks!

**Comment by nerdralph** [comment]
> merged most (if not all) of this into 110. Thanks!
	
Niets te danken!
