### ISSUE TITLE
GPU usage control

### ISSUE THREAD

**Issue by Nelovep** [Genoil/cpp-ethereum#85]
Can you add GPU usage control comand? For example: I want to use 1/2 of my card power to mining.

**Comment by nerdralph** [comment]
You can already get a bit of control over GPU load with the --cl-global-work option.  384 will drop your hashrate to around 1/2 compared to the default 4096.

**Comment by Nelovep** [comment]
thank you very much

**Comment by CHANPHUONG** [comment]
ok

**Comment by CHANPHUONG** [comment]
Ok
