### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by nerdralph** [Genoil/cpp-ethereum#87]
It took a lot more work than I expected, but it's finally here.
https://github.com/nerdralph/ethminer-nr/blob/110/releases/ethminer-genoil-1.1.8nr.tgz

All ethminer's "special" dependencies are statically linked, so it should work on any Linux platform that claymore does, although it has only been tested on Ubuntu 14.04.

**Comment by NicolasCARPi** [comment]
Hello,

On Archlinux 64 here is the output:
./ethminer: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./ethminer)
./ethminer: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by ./ethminer)
./ethminer: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by ./ethminer)

Regards,
~Nico

**Comment by nerdralph** [comment]
I should have mentioned this is an AMD-only build (no cuda).
I've already been investigating the curl dependency, and I think the original build recommendation of libcurl4-gnutls-dev is wrong.  The curl dependency comes from libjson-rpc-cpp, and that depends on libcurl4-openssl-dev.
https://packages.debian.org/source/sid/libjson-rpc-cpp

I've confirmed a build using shared linking with libcurl4-openssl-dev works good, and I'm working on a new build statically linking libcurl.a.

**Comment by nerdralph** [comment]
@NicolasCARPi I just released a new static build (1.1.9)that does not depend on CURL, but I haven't looked into the "no version information" error for libOpenCL.so.1 yet.

**Comment by soulmachine** [comment]
can you make a cuda version ?

**Comment by nerdralph** [comment]
@soulmachine  I have no Nvidia cards, so there's not much point in doing a cuda build when I can't test it.
