### ISSUE TITLE
please help , CUDA mining not working 

### ISSUE THREAD

**Issue by kilid** [Genoil/cpp-ethereum#88]
I tried to do the following , but it is not working 

Building on Windows

download or clone this repository
download and install Visual Studio 12 2013 and CMake
run getstuff.bat in cpp-ethereum/extdep
open a command prompt and navigate to cpp-ethereum directory
mkdir build 
cd build
cmake -DBUNDLE=cudaminer -G "Visual Studio 12 2013 Win64" ..
if you don't want/need CUDA support, use "miner" instead of "cudaminer". This will only compile OpenCL support
to speed up compilation a bit, you can add -DCOMPUTE=xx , where x is your CUDA GPU Compute version * 10. i.e -DCOMPUTE=52 for a GTX970.
you may disable stratum support by adding -DETH_STRATUM=0
When CMake completes without errors, opn ethereum.sln created in the build directory in Visual Studio
Set "ethminer" as startup project by right-clicking on it in the project pane
Build. Run

the error I am getting is when I type this 
cmake -DBUNDLE=cudaminer -G "Visual Studio 12 2013 Win64" ..
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Khalid> cd\

C:\>cd cpp-ethereum-master

C:\cpp-ethereum-master>cd build

C:\cpp-ethereum-master\build>cmake -DBUNDLE=cudaminer -G "Visual Studio 12 2013
Win64"
'cmake' is not recognized as an internal or external command,
operable program or batch file.

C:\cpp-ethereum-master\build>cmake -DBUNDLE=cudaminer -G "Visual Studio 12 2013
Win64"
'cmake' is not recognized as an internal or external command,
operable program or batch file.

C:\cpp-ethereum-master\build>

**Comment by mailming** [comment]
Need to install cmake first, 

https://cmake.org/

This is not a bug.

**Comment by kilid** [comment]
After that how do i start mining ? 

Regards,
Khalid Al Ghamdi 
0097333454988
0097332100046

**Comment by eth100tx** [comment]
You only need to build if you're experimenting with the code.  If you just want to mine, pull a pre-build image from:
  https://github.com/Genoil/cpp-ethereum/tree/110/releases
