### ISSUE TITLE
eth-miner fails to build on Win7 (x64), Visual Studio 2015

### ISSUE THREAD

**Issue by SethVgr** [Genoil/cpp-ethereum#89]
# Checklist
- [done ] downloaded the repo and dependencies 
```
git clone https://github.com/Genoil/cpp-ethereum.git
cd cpp-ethereum
cd extdep
getstuff.bat 
```

I have visual studio 2015 so I created the configuration (solution) files as follows:

```
mkdir build
cd build
cmake.exe -DBUNDLE=cudaminer -G "Visual Studio 14 2015 Win64" ..
```
I have the solution files but when I try to build from Visual Studio, the project "ethminer" I get ~2000 errors such as:

```
Severity    Code    Description Project File    Line    Suppression State
Error   C2206   'swap': typedef cannot be used for function definition (compiling source file C:Ethereum-Miner\cpp-ethereum\libdevcore\Common.cpp)  devcore C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility  21  
Error   C2988   unrecognizable template declaration/definition (compiling source file C:Ethereum-Miner\cpp-ethereum\libdevcore\Common.cpp)  devcore C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility  35  
Error   C2059   syntax error: ')' (compiling source file C:Ethereum-Miner\cpp-ethereum\libdevcore\Common.cpp)   devcore C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility  35  
Error   C2065   '_Ty': undeclared identifier (compiling source file C:Ethereum-Miner\cpp-ethereum\libdevcore\Common.cpp)    devcore C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility  50  
Error   C2923   'std::is_nothrow_move_constructible': '_Ty' is not a valid template type argument for parameter '_Ty' (compiling source file C:Ethereum-Miner\cpp-ethereum\libdevcore\Common.cpp)   devcore C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility  50  
Error   C2923   'std::is_nothrow_move_assignable': '_Ty' is not a valid template type argument for parameter '_Ty' (compiling source file C:Ethereum-Miner\cpp-ethereum\libdevcore\Common.cpp)  devcore C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\utility  50  
```

## System/environment

- OS:  Win7 x64

## Expected behaviour

**ethminer** should build

## Observed behaviour

Build fails. What am I missing?

**Comment by eth100tx** [comment]
1) use branch 110
git checkout 110
you can verify with "git branch" which should show 110 and master with a * in front of 110

2) use Visual Studio 12 2013
didn't look at why, just pulled the older ver and reinstalled and it worked

3) when it builds
The executable is in build\ethminer\Debug
it will fail due to missing "libcurl.dll". copy libcurld.dll to libcurl.dll in the directory and it should run

**Comment by SethVgr** [comment]
Thanks, I guess it's no use trying to tweak it from VS 2015. I think it's because of the different standard of C++ VS 2015 is using.

**Comment by SethVgr** [comment]
Thanks, I'll try with the earlier version of VS.

**Comment by Genoil** [comment]
You're welcome to make it VS2015 compatible, but for now, this is not a point of focus.
