### ISSUE TITLE
update documentation to point to new locations

### ISSUE THREAD

**Issue by kyle-downey** [Genoil/cpp-ethereum#9]
Currently a number of documation links reference the old cpp-ethereum, and thus they all hit the same redirect to webthree-umbrella, e.g. the build link should probably reference this:

https://github.com/ethereum/webthree-umbrella/wiki

which has links for Ubuntu, OSX, etc. builds, or maybe do a deep link to each individual page.

TODO list I cannot find, so that probably should just be removed from README.md.

Happy to send a pull request for this, and will update my blog HOWTO page:

http://www.cloudwall.io/mining-ether

**Comment by Genoil** [comment]
Apparently ETH:DEV is resurrecting cpp-ethereum and possibly merging some of my changes back upstream. Until then , I've included a basic standalone readme with build instructions.
