### ISSUE TITLE
sm_20 support

### ISSUE THREAD

**Issue by cbasah** [Genoil/cpp-ethereum#90]
Hi there,

Is there a reason why the current master branch has sm_20 (Femi) support removed from libethash-cuda/CMakelists.txt? Earlier versions had it.

Branch 110 has it which I compiled but when I ran it, I got the following run-time error:

**Using device: Tesla M2050 (Compute 2.0)
Using device: Tesla M2050 (Compute 2.0)
 m  15:09:27|ethminer  Mining on PoWhash #db64348b : 0.00MH/s [A0+0:R0+0:F0]
Generating DAG for GPU #0
Generating DAG for GPU #1
Cuda error in func 'ethash_generate_dag' at line 129 : uncorrectable ECC error encountered.**

I then disabled ECC via 'nvidia-smi -e 0' and now encountered the following error:
**Cuda error in func 'ethash_generate_dag' at line 129 : unspecified launch failure.**

I am running Ubuntu 14.04.

Many thanks for writing the cuda-supporting ethminer.

**Comment by Genoil** [comment]
I disable it because most people don't need it. Havent tested 110 branch against 2.0 yet, never seen that error before..,

**Comment by eth100tx** [comment]
The May 25th commit of build of 110 works for compute 2.0 on M2090s
  https://github.com/Genoil/cpp-ethereum/commit/283ba9ea99fa8db664e8dcba37700536a882f204

looks like CUDA 7.5 with some minor changes to build
  https://github.com/ethereum/webthree-umbrella/issues/315#issuecomment-225399356
