### ISSUE TITLE
[BUG] genoil 0.9.41 and 1.0.5 CUDA fail to run on Windows 7 x64

### ISSUE THREAD

**Issue by SethVgr** [Genoil/cpp-ethereum#91]
# Checklist
- [done ] downloaded a prebuild for windows from [here](https://github.com/Genoil/cpp-ethereum/tree/master/releases) (the CUDA [version](https://github.com/Genoil/cpp-ethereum/tree/master/releases/cuda-6.5))

Ran the following to mine on nanopool:

ethminer.exe -F http://eth1.nanopool.org:8888/0x154230ed91d1e711e56b9c0f88b5ba5fd2b0503f -G

## System/environment

- OS:  Win7 x64

## Expected behaviour

**ethminer** should start mining and submit hash rates and shares

## Observed behaviour

**ethminer** is stuck in an impossible to connect loop:

```
Genoil's ethminer 0.9.41-genoil-1.0.5
=====================================================================
Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from RoBiK, tpruvot and sp_
 
Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d
 
Found suitable OpenCL device [GeForce GTX 770M] with 3221225472 bytes of GPU mem
ory
miner  18:54:16|main  Getting work package...
  X  18:54:19|main  Failed to submit hashrate.
  X  18:54:19|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error:
5
 
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  18:54:23|main  Getting work package...
  X  18:54:26|main  Failed to submit hashrate.
  X  18:54:26|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error:
5
 
JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  18:54:30|main  Getting work package...
```

Looking up the error code (5) in libcurl:

```
CURLE_COULDNT_RESOLVE_PROXY (5)

Couldn't resolve proxy. The given proxy host could not be resolved.
```

but I am not using any proxy settings? Is ethminer launched correctly? Bench marking with the flags -M and -G set produces a hash rate.

**Comment by Genoil** [comment]
Rtfm

**Comment by SethVgr** [comment]
I did rtfm. It's pretty fu***** useless.

**Comment by Genoil** [comment]
lol yeah it is. i misread your post, sorry. dunno what is wrong with this. anyway, try 1.0.8 or 1.1.7 and use a stratum connection. it's much better.
