### ISSUE TITLE
Random over time bug

### ISSUE THREAD

**Issue by Bobidobi** [Genoil/cpp-ethereum#92]
Hello. I have setup for mining with pool on dwarfpool using genoil 1.1.7 with stratum and cuda active. Im using prebuilt from [https://github.com/Genoil/cpp-ethereum/tree/110/releases](url)
My parameters:
"ethminer -U -S eth-eu.dwarfpool.com:8008 -FS eth-ru.dwarfpool.com:8008 -SP 1 -O MY_WALLET.MY_WORKER --farm-recheck 2000 --cuda-grid-size 2048"
It sending shares at the beginning, they even show up on a site, but eventually fails and showing every (i mean all of them, not occasionally one or two) share like this:

>   i  23:29:16|cudaminer0  Solution found; Submitting to eth-eu.dwarfpool.com ...
> 
>   i  23:29:16|cudaminer0    Nonce: 0x1164b24c0c3daeda
>   X  23:29:16|stratum  :-( Not accepted.

P.S. Sorry for my bad english.

**Comment by Genoil** [comment]
I can confirm this behavior. I only get it at dwarfpool, not sure what causes this.
