### ISSUE TITLE
A known issue or does it kill my GPU?

### ISSUE THREAD

**Issue by yaapelsinko** [Genoil/cpp-ethereum#95]
I'm using 1.1.7 miner and Fury X at 16.9.1 drivers.

Constantly having an issue with BSOD (usually "thread stuck in device driver" stop-code) when the miner is running and:
a) starting a video from file
b) watching youtube videos
c) browsing twitter (with Edge, at least)

Though it doesn't happens 100% of time, but still often enough to see the tendency.

What is weird is that the problem did not appeared at first. Then it appeared on twitter. Then on videos. It looks like it happens more often now (maybe related to growing memory usage?). 

What's happening?! O.O

**Comment by jch9678** [comment]
Probably a bad riser if it's on one, but you'll have better luck asking in the ethereum forums.

https://forum.ethereum.org/categories/mining

**Comment by yaapelsinko** [comment]
Meh, no luck with that. No replies.

Nope, I don't use a riser, it's just a PC I use for what PC are usually used to.

By the way, I can play games (those not too heavy) while mining, no problems with that. Like, at all. The new MoO, EVE, KSP. But the symptom with twitter, for example, has definitely become worse. It was pretty rare issue once, but now if I open my twitter feed, it summons BSOD almost immediately if there is an embedded video (you know, those short clips with volume out loud).

**Comment by yaapelsinko** [comment]
Meh, no luck with that. No replies.

Nope, I don't use a riser, it's just a PC I use for what PC are usually used to.

By the way, I can play games (those not too heavy) while mining, no problems with that. Like, at all. The new MoO, EVE, KSP. But the symptom with twitter, for example, has definitely become worse. It was pretty rare issue once, but now if I open my twitter feed, it summons BSOD almost immediately if there is an embedded video (you know, those short clips with volume out loud).

**Comment by Genoil** [comment]
I'm really sorry but I like to keep this section free of operational support requests. This section is for issues with the code...

**Comment by yaapelsinko** [comment]
Well I don't know if it operational or code, but it seems the issue only appears when I mine ETH, and not ETC...
